95 cli step 5 b04 anglepy
brown-ccv/icesat2-tracks pull request #111
Opened 2024-02-06 20:30 UTC by cpaniaguam

TODO: choose better name? @mochell 
#95

2024-02-07 21:02 UTC, hollandjg requested changes
Thanks for this! I've got a few more comments here.

2024-02-07 21:41 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +        def plot_instance(
Indeed, that function, and a number of others in this file, do use variables defined in the scope.  Fixing this entails significant effort. It's almost a `wont-fix` for me.

2024-02-07 21:44 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +            ax3 = F.fig.add_subplot(gs[2, 0:-1]) # can the assignment be removed? CP
It's hard to say if it'll work the same way without granular tests. I think `add_subplot` creates a side effect and returns `None` but I'm speculating.

2024-02-07 21:45 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +            SM.fitting_kargs = {"prior": prior_sel, "prior_weight": 3} # not sure this might be used somewhere. CP
Not easy to say. I'll just leave there for now.

2024-02-07 21:50 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +from numba import jit # maybe for later optimizations?  # noqa: F401
I'll comment the line to keep it as a reminder and avoid loading the unused module.

2024-02-07 21:52 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +    with suppress_stdout(verbose):
I was intending to suppress all the output! Note that the rest of the code is within the scope of the context manager.

2024-02-09 17:30 UTC, kmilo9999 reviewed
I like the new changes 👍  . It looks good to me. The merge conflicts need to get solved before merging.

2024-02-12 20:08 UTC, hollandjg approved these changes
Looks good to me!

2024-02-16 23:51 UTC, merged