Cli step 7 b06 correct
brown-ccv/icesat2-tracks pull request #113
Opened 2024-02-07 20:40 UTC by kmilo9999

2024-02-15 22:35 UTC, cpaniaguam requested changes
Great work on getting the cli set up and making the paths work! Thanks Camilo!!

I pointed out some opportunities for refactoring the code. Some reflect my personal style (like moving a block of code to a function) but a number of others will make the code more pythonic. Let me know what you think!

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        ):
Some comments here would be nice to have!

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        F.save_pup(path=plot_path, name=str(track_name) + "_B06_atten_ov")
Maybe another function for this plot?

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            return height_model, np.nan, dist_nanmask
Can these safely be put at the top?

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            G_height_model[bb] = xr.concat(G_height_model_temp.values(), dim="x").T
This block seems like a good candidate to move to a function. What do you think?

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            G_height_model[bb] = xr.concat(G_height_model_temp.values(), dim="x").T
Probably up to L587.

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            Gx_v2[bb] = Gx_k
This other block looks like it's its own entity.

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            )
This is likely the error prone line. Consider using an [else block ](https://docs.python.org/3/tutorial/errors.html#:~:text=The%20try%20%E2%80%A6%20except%20statement%20has%20an%20optional%20else%20clause%2C%20which%2C%20when%20present%2C%20must%20follow%20all%20except%20clauses.%20It%20is%20useful%20for%20code%20that%20must%20be%20executed%20if%20the%20try%20clause%20does%20not%20raise%20an%20exception.%20For%20example%3A).

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        except:
And here consider adding an exception. Maybe something like along the lines:
```python
try:
    # some code that might raise an exception
except ValueError as e:
    print(f"A ValueError occurred: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
else:
    # code to run if no exception was raised
```

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            x_corrected = Gk.x * np.cos(theta) * np.nan
I would put this in a function also.

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        Gk_v2.attrs["best_guess_incident_angle"] = theta
This block seems to be for computing `Gk_v2`; I would put it in a function.

2024-02-15 22:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +                io.save_pandas_table(data, tablename, save_path)
Can this function be move to the top?

2024-02-16 15:55 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>      x2, y2 = xx, dd
I dont know if this is intentional or not, but it seems that `piecewise_regression.Fit` modifies the argument `x2`. The arguments the `get_breakingpoints` is called with are used later in the code and they need to be on a specific state.

2024-02-16 16:10 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        G_fft_wmean["N_per_stancil"] = Gfft["N_per_stancil"].sum("beam")
I just realized the `G_fft_wmean`  is not used in the rest of code. I am removing it, but still created the function.

2024-02-16 16:16 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        ).sum("beam") / Gk["N_per_stancil"].sum("beam")
This two assignments are the same. Therefore, the second operation is redundant ? Im removing it.

2024-02-16 16:24 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        gFT_PSD_data_error_mean = xr.concat(G_error_data.values(), dim="beam")
I replaced it with a single line assignment

2024-02-16 16:25 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            ).expand_dims("beam")
I removed the second operation

2024-02-16 16:27 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            echo("--------------------------")
Love this code!!

2024-02-16 16:42 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +                ialpha = next(alpha_range)
You mean, taking the `ialpha = next(alpha_range)` assingment out of the loop?

2024-02-16 16:48 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            return height_model, np.nan, dist_nanmask
Yes, they can. `fit_offset` is not used, I removed it.

2024-02-16 17:06 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            ).expand_dims("beam")
I think the operations the same but they seem to be defining different objects using different input. Namely, the first one is defining/updating `G_error_model[bb]`, while the second one does something to the same effect for `G_error_data[bb]`. Note also that the `data` argument is also different.

2024-02-16 17:12 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>      x2, y2 = xx, dd
Interesting.

2024-02-16 17:15 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +                ialpha = next(alpha_range)
Correct!

2024-02-16 17:21 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +                ialpha = next(alpha_range)
Wait though: `next` is actually consuming the `alpha_range` itereator in every iteration so `ialpha` actually changes. It's better to use `zip` in the for loop:
```python
            for x, ialpha in zip(Gplot.x.data, alpha_range):
```

2024-02-16 17:25 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        gFT_PSD_data_error_mean = xr.concat(G_error_data.values(), dim="beam")
Actually, it seems like `gFT_PSD_data_error_mean` is getting overwritten in L255. Are you deleting L254?

2024-02-16 19:30 UTC, kmilo9999 commented on src/icesat2_tracks/app.py
> +@app.command(help=_run_B04_angle.__doc__)
fixed

2024-02-16 19:32 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>      for i in pw_results.keys():
I applied all these changes.

2024-02-16 19:39 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        except:
Done

2024-02-16 19:40 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        Gk_v2.attrs["best_guess_incident_angle"] = theta
#117

2024-02-16 19:40 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +                io.save_pandas_table(data, tablename, save_path)
Done

2024-02-16 19:40 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>      br_points_sorted["breakpoint" + str(br_points_sorted.size + 1)] = "end"
Done

2024-02-16 19:45 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>      x2, y2 = xx, dd
Fixed

2024-02-16 19:45 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    output_dir: str = typer.Option(None, callback=validate_output_dir),
Fixed

2024-02-16 19:45 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    report_input_parameters(**kargs)
Fixed

2024-02-16 19:46 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            B3[b] = io.get_beam_hdf_store(B3_hdf5[b])
Fixed

2024-02-16 19:47 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    kargs = {
Fixed

2024-02-16 19:50 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        B3_hdf5 = h5py.File(h5_file_path, "r")
Fixed

2024-02-16 19:50 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            load_path_work / "B02_spectra" / ("B02_" + track_name + "_gFT_x.nc")
Fixed

2024-02-16 19:52 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        G_fft_wmean["N_per_stancil"] = Gfft["N_per_stancil"].sum("beam")
Done

2024-02-16 19:53 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        ).sum("beam") / Gk["N_per_stancil"].sum("beam")
Done

2024-02-16 19:54 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        gFT_PSD_data_error_mean = xr.concat(G_error_data.values(), dim="beam")
Fixed. We removed the first assignment

2024-02-16 19:55 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            ).expand_dims("beam")
removed the first assignment

2024-02-16 19:55 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            echo("--------------------------")
Done

2024-02-16 19:59 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +                ialpha = next(alpha_range)
Done

2024-02-16 20:10 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        ):
It's unclear what this piece of code does.

2024-02-16 20:10 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>      br_points_sorted["breakpoint" + str(br_points_sorted.size + 1)] = "end"
Done

2024-02-16 20:11 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>          )
Unclear what the code does

2024-02-16 20:13 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
>      pw_fit, breakpoint_log = get_breakingpoints(k_log, data_log.data)
Done

2024-02-16 20:14 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            Gplot = Gplot.where(Gplot["N_per_stancil"] / Gplot["Lpoints"] >= 0.1)
TODO #119

2024-02-16 20:15 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            return height_model, np.nan, dist_nanmask
Done

2024-02-16 20:16 UTC, kmilo9999 commented on .github/workflows/test-B01_SL_load_single_file.yml
done

2024-02-16 20:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            G_height_model[bb] = xr.concat(G_height_model_temp.values(), dim="x").T
TODO

2024-02-16 20:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            G_height_model[bb] = xr.concat(G_height_model_temp.values(), dim="x").T
#120

2024-02-16 20:18 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            Gx_v2[bb] = Gx_k
TODO

2024-02-16 20:18 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            Gx_v2[bb] = Gx_k
#121

2024-02-16 20:18 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            )
Done

2024-02-16 20:19 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            )
Done

2024-02-16 20:24 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +            x_corrected = Gk.x * np.cos(theta) * np.nan
Done

2024-02-16 20:36 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        Gk_v2.attrs["best_guess_incident_angle"] = theta
#122

2024-02-16 22:37 UTC, cpaniaguam approved these changes
Great work, thanks!

2024-02-16 22:41 UTC, merged