112 cli step 6 b04 define angle
brown-ccv/icesat2-tracks pull request #115
Opened 2024-02-12 20:01 UTC by cpaniaguam

#112

2024-02-15 20:25 UTC, kmilo9999 requested changes
It looks good to me. Just a few comments.

2024-02-15 20:25 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +def convert_to_kilo_string(x):
This function is only called once. As it is just a single line function, we can avoid the overhead of calling function by replacing it by just the single line

2024-02-15 20:25 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +            x_str = convert_to_kilo_string(xval)
```suggestion
            x_str = str(int(x / 1e3))
```

2024-02-15 20:25 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +def update_axes(ax, x_ticks, x_tick_labels, xlims):
This function is only called once, and it's not doing any complicated logic. We can just move the assignments where this function is called

2024-02-15 20:25 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +            update_axes(ax, x_ticks, x_tick_labels, xlims)
This `update_axes `function seems to be unnecessary.

```suggestion
          ax.set_xticks(x_ticks)
          ax.set_xticklabels(x_tick_labels)
          ax.set_xlim(xlims))
```

2024-02-15 20:25 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +    hemis, batch = batch_key.split("_")
The second retuned values doesnt seem to be used in the rest of the code
```suggestion
    hemis, _= batch_key.split("_")
```

2024-02-15 20:44 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +def convert_to_kilo_string(x):
I see what you mean and that is probably the c++ developer in you! Have you read the Zen of Python?

```python
>>> import this
```

What do you think is more readable, `convert_to_kilo_string(x)` or `str(int(x / 1e3))`? The gain in readability probably outweighs the relatively small overhead of defining the function. Let me know what you think about the Zen of Python!

2024-02-15 20:51 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +            update_axes(ax, x_ticks, x_tick_labels, xlims)
In the spirit of making the code more readable and seeing fewer lines of code mid script, I thought this was a reasonable abstraction. @hollandjg What do you think?

2024-02-16 14:47 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +def convert_to_kilo_string(x):
What about just placing a comment about the code explaining what it does?
The logic is simple and I dont see any other part of the code that this function is needed. 
Also, I wonder if we can rename the function. I assume `kilo` means kilometers, and just because of pure intuition. Naming argument as `x` really doesn't have any context.

2024-02-16 14:47 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +            update_axes(ax, x_ticks, x_tick_labels, xlims)
What about moving the `for` loop inside the function?
My personal opinion is that functions that only makes assignments look alike object's constructors functions.

2024-02-16 19:08 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +def convert_to_kilo_string(x):
We decided to leave the function

2024-02-16 19:11 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +            update_axes(ax, x_ticks, x_tick_labels, xlims)
Let's leave the function.

2024-02-16 21:07 UTC, kmilo9999 approved these changes
All good

2024-02-16 23:28 UTC, merged