Cleaning and formating files in the ICEsat2_SI_tools folder
brown-ccv/icesat2-tracks pull request #132
Opened 2024-02-26 16:32 UTC by kmilo9999

2024-02-26 17:12 UTC, hollandjg requested changes
Nice! I've got a few comments and suggestions here.

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
>  def get_leaps():
We could replace this with a call to the timezone database: https://stackoverflow.com/a/33445945/5542581

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/iotools.py
> +        block2 = (self.TRK, self.CYC, "01")
This feels like a comment to keep:
```suggestion
        block2 = (self.TRK, self.CYC, "01")  # granule is always '01' for ATL10
```

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
> +    data_lp = signal.convolve(data, L, mode=mode, method=method)  # *
```suggestion
    data_lp = signal.convolve(data, L, mode=mode, method=method)
```

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
>      import scipy.signal as signal
Do we want to move this to the top of the file?

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
> +    data_lp = signal.convolve(data, L2d, mode=mode)  # *
```suggestion
    data_lp = signal.convolve(data, L2d, mode=mode)
```

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
> +    data_lp = signal.convolve(data, L3d, mode=mode)  # *
```suggestion
    data_lp = signal.convolve(data, L3d, mode=mode)
```

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spicke_remover.py
>      This function removes spickes from timeseries based on its std and maximum values
```suggestion
    This function removes spikes from timeseries based on its std and maximum values
```

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>      # cal variance
```suggestion
```

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        G_LS_power = xr.concat(G_LS_power.values(), dim="x").T  # .to_dataset()
```suggestion
        G_LS_power = xr.concat(G_LS_power.values(), dim="x").T
```

2024-02-26 17:12 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        G_fft = xr.concat(G_fft.values(), dim="x").T  # .to_dataset()
```suggestion
        G_fft = xr.concat(G_fft.values(), dim="x").T
```

2024-02-26 20:53 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        G_fft = xr.concat(G_fft.values(), dim="x").T  # .to_dataset()
removed

2024-02-26 20:53 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        G_LS_power = xr.concat(G_LS_power.values(), dim="x").T  # .to_dataset()
removed

2024-02-26 20:53 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>      # cal variance
removed

2024-02-26 20:53 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spicke_remover.py
>      This function removes spickes from timeseries based on its std and maximum values
changed

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
> +    data_lp = signal.convolve(data, L3d, mode=mode)  # *
removed

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
> +    data_lp = signal.convolve(data, L2d, mode=mode)  # *
removed

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
>      import scipy.signal as signal
moved

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
> +    data_lp = signal.convolve(data, L, mode=mode, method=method)  # *
removed

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/iotools.py
> +        block2 = (self.TRK, self.CYC, "01")
comment added

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
>  def get_leaps():
Are you sure? He is testing against specific values.

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> -    ax5 = plt.subplot(gs[0:2, 2])
That variable was not being used in the code.

2024-02-26 20:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
>      ---not well testet ---
changed

2024-02-27 14:34 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +    import numpy as np
removed

2024-02-27 20:20 UTC, cpaniaguam requested changes
I added a number of refactorings and suggestions.

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # self.calc_var(self)
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>  class wavenumber_spectrogram_LS_even:
Rename this class as per PEP 8?

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # print(waven_method)
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # dy_fake= np.random.randn(len(dy))*0.001 if self.dy is not None else None
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # x = X[x_mask]
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            y = detrend(idata)  # * win
```suggestion
            y = detrend(idata)
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            )
```suggestion
        G = {
            xi: xr.DataArray(
                I,
                dims=["k"],
                coords={"k": self.k, "x": xi * self.dx},
                name=self.spec_name,
            )
            for xi, I in D_specs.items()
        }
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        self.G = xr.concat(G.values(), dim="x").T  # .to_dataset()
```suggestion
        self.G = xr.concat(G.values(), dim="x").T
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>  class wavenumber_spectrogram_LS:
Rename class?

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # print(waven_method)
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # self.k, self.dk  = self.k[::kjumps], self.dk*kjumps
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
Some imports not at the top.

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +                # return stancil[1], self.k*np.nan, np.fft.rfftfreq( int(self.Lpoints), d=self.dx)*np.nan,  x.size
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>              # print('--')
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # P.test_ojective_func(P.tanh_weight_function, plot_flag=False)
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # Spec_returns = list(map( calc_spectrum_and_field_apply, copy.copy(self.stancil_iter)   ))
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>          # Spec_returns=list()
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # print(I[1].shape, I[2].shape)
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # self.calc_var(self)
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>  class wavenumber_pwelch:
Rename class?

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # M.figure_axis_xy()
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # print('iter range', np.arange(0,data.size,int(L-ov)))
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # print(chunk.size, l)
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # print(self.phi.max())
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>                  #    MT.stats_format(self.spec, 'spec '+str(i))
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +                    # MT.stats_format(self.phi, 'chunk '+str(i))
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>              # plt.plot(abs(v2_fft) , linewidth=2, alpha=0.5 , c='black', label='org data (var: '+str(v2) +')')
```suggestion
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            rr[int(i)] = np.nanmean(var[i - m : i + m])
```suggestion
        var_range = np.arange(m, int(s[0]) - m - 1, 1)
        for i in var_range[np.isfinite(var[m : int(s[0]) - m - 1])]:
            rr[int(i)] = np.nanmean(var[i - m : i + m])
```

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spicke_remover.py
Some chuncks of commented out code here.

2024-02-27 20:20 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/wave_tools.py
Some imports at the top.

2024-02-27 20:40 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        track_lon_end.append(ll["lons"])
I'm not sure the list comprehension is more readable – I think I can understand the for-loop version more quickly than the list comprehension, at least.

2024-02-28 14:45 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
>  import pdb
Can you point to the commented line? I cant find it.

2024-02-28 14:58 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        raise ValueError("some defintions went wrong")
Very adult/pro-code. I'm learning a lot here.

2024-02-28 15:31 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>          T_sets.append(T_merged)
You are gonna have to walk me through the process on doing it.

2024-02-28 15:53 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    # print([xleft[0:max_size], xcenter_pos[0:max_size], xright[0:max_size]])
Weird, I dont see those comments in my local repo

2024-02-28 15:58 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>          T_sets.append(T_merged)
It'd be my pleasure! Note that the for loop is creating this `T_merged` object that depends on `stancil_set`, `T2`, `stancil_set`, `key_var`, `key_x_coord`, and `stancil_width`. You could create a function to refactor the body of the for loop upto but not including the last line that appends `T_merged` to `T_sets`. For this you could use VS code refactor tool to extract a method. With the function defined you can do something like 
```python
T_sets = [newfunction(stancil_set, *args) for stancil_set in [stencil_1, stencil_1half]
```

2024-02-28 21:34 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/wave_tools.py
moved imports to the top

2024-02-28 21:35 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            rr[int(i)] = np.nanmean(var[i - m : i + m])
Removed commented line

2024-02-28 21:35 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>              # plt.plot(abs(v2_fft) , linewidth=2, alpha=0.5 , c='black', label='org data (var: '+str(v2) +')')
Removed

2024-02-28 21:35 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +                    # MT.stats_format(self.phi, 'chunk '+str(i))
Removed

2024-02-28 21:35 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>                  #    MT.stats_format(self.spec, 'spec '+str(i))
Removed

2024-02-28 21:36 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # print(self.phi.max())
Removed

2024-02-28 21:36 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # print(chunk.size, l)
Removed

2024-02-28 21:36 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # print('iter range', np.arange(0,data.size,int(L-ov)))
Removed

2024-02-28 21:36 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # M.figure_axis_xy()
Removed

2024-02-28 21:37 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>  class wavenumber_pwelch:
renamed to WavenumberPwelch

2024-02-28 21:37 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # self.calc_var(self)
Removed

2024-02-28 21:37 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # print(I[1].shape, I[2].shape)
Removed

2024-02-28 21:37 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>          # Spec_returns=list()
Removed

2024-02-28 21:37 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # Spec_returns = list(map( calc_spectrum_and_field_apply, copy.copy(self.stancil_iter)   ))
Removed

2024-02-28 21:38 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # P.test_ojective_func(P.tanh_weight_function, plot_flag=False)
Removed

2024-02-28 21:38 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>              # print('--')
Removed

2024-02-28 21:38 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +                # return stancil[1], self.k*np.nan, np.fft.rfftfreq( int(self.Lpoints), d=self.dx)*np.nan,  x.size
Removed

2024-02-28 21:38 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
Moved imports to the top

2024-02-28 21:39 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # self.k, self.dk  = self.k[::kjumps], self.dk*kjumps
Removed

2024-02-28 21:39 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>  class wavenumber_spectrogram_LS:
Changed to WavenumberSpectrogramLS

2024-02-28 21:39 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            )
Done

2024-02-28 21:40 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            y = detrend(idata)  # * win
Removed

2024-02-28 21:40 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            # x = X[x_mask]
Removed

2024-02-28 21:40 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # dy_fake= np.random.randn(len(dy))*0.001 if self.dy is not None else None
Removed

2024-02-28 21:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # print(waven_method)
Removed

2024-02-28 21:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>  class wavenumber_spectrogram_LS_even:
Changed to `WavenumberSpectrogramLSEven`

2024-02-28 21:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # self.calc_var(self)
Removed

2024-02-28 21:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>          # print(self.dk)
Removed

2024-02-28 21:42 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    # print(map_func)
Removed

2024-02-28 21:42 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # print(stancil[1])
Removed

2024-02-28 21:42 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    # factor=np.sqrt( L/(win**2).sum())
Removed

2024-02-28 21:42 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        # win=np.hanning(L)
Removed

2024-02-28 21:43 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            f = df * np.arange(df, N)
Done

2024-02-28 21:43 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
Done

2024-02-28 21:43 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>      returns all need chunk boudaries and center position given L, and ov
Done

2024-02-28 21:43 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    # print(ov)
I added a new implementation of this function that modifies the boundary according to the parameter type. Let me know your thoughts.

2024-02-28 21:44 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    neven = True if (N % 2) else False
I added a new function called `is_even`. Let me know your thoughts

2024-02-28 21:44 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>          return position_stancil
Done

2024-02-28 21:44 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    # print([xleft[0:max_size], xcenter_pos[0:max_size], xright[0:max_size]])
Deleted

2024-02-28 21:44 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/read_ground_tracks.py
>      return geopandas.pd.concat(GTs)
Done

2024-02-28 21:45 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/read_ground_tracks.py
Done

2024-02-28 21:45 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
Done

2024-02-28 21:46 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>          N_i.append(i_mask.sum())
Both operations depend on the `i_mask`  value

2024-02-28 21:46 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +    ilim = int(len(dist_grid))
Done

2024-02-28 21:46 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        np.isnan(DF_filt[key + "_std"])
Done

2024-02-28 21:46 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        print(str(istencil[1]) + " s" + str(time.time() - tstart))
Done

2024-02-28 21:46 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        Tmedian[key + "_std"] = y.std()
Done

2024-02-28 21:47 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>      stancil_set = stencil_1
Removed

2024-02-28 21:47 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>      import pandas as pd
moved to the top

2024-02-28 21:47 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +    # @jit(nopython=True, parallel= False)
removed

2024-02-28 21:48 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +# @jit(nopython=True)
removed

2024-02-28 21:48 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        x1 = np.arange(0, TT["dist"].max(), dx)
Done

2024-02-28 21:48 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +
Removed

2024-02-28 21:49 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        TT["dist"] = TT["dist"]  # - lat_lims[0]
Done

2024-02-28 21:49 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        track_lat_maxs.append(B[k]["lats"].max())
Done

2024-02-28 21:49 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +        hemis = "NH"
Done

2024-02-28 21:50 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>  def lat_min_max(B, beams_list, accent=None):
Fixed the typos

2024-02-28 21:50 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>          track_lon_start
Done

2024-02-28 21:50 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
Done

2024-03-01 12:53 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
>  import pdb
removed pdb import

2024-03-01 12:54 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>          T_sets.append(T_merged)
I refactorized that part of the code moving it to a new function.

2024-03-01 12:54 UTC, kmilo9999 commented
@cpaniaguam @hollandjg Check my replies on the opened conversations and do a last review.

2024-03-01 15:27 UTC, hollandjg requested changes
Thanks for this! It looks like there are more changes here than just cleaning and formatting – some of the changes to functions look like they need more detailed tests before we can make them. 
Is it possible to split this into a PR which does just cleanup, and another (or several) which make functional changes?

2024-03-01 15:27 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/A01b_ALT07_SHNH_variance_tester.py
> +    iter_x = spec.create_chunk_boundaries( Lmeter, [ xx.min(), xx.max()],ov =Lmeter*3/4, iter_flag= False)[1,:]
It looks like you're using a different function here – is that intentional?

2024-03-01 15:27 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    return boundaries
This looks like you're replacing a few different functions with a single dispatch. I'm not sure that this makes it easier for future users to maintain this code.  And are you sure that this works the way you think? `singledispatch` only checks the type of the first argument, not the other arguments (python doesn't have built-in multiple-dispatch).

2024-03-01 15:27 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> -def create_chunk_boundaries_unit_lengths(L_unit, data_limits, ov= None,  iter_flag=True):
This looks to have a different signature than the `create_chunk_boundaries` – are you sure they are identical?

2024-03-01 15:27 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        neven = is_even(N)
I'm not sure this is correct. 
```
let N = 2
N % 2 --> 0 --> False
is_even(N) --> True  ! (Mismatch between old and new behavior.)
```

2024-03-01 15:27 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        self.stancil_iter_list = spec.create_chunk_boundaries(
It looks like you're using a different function here.

2024-03-01 15:27 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
This file seems to have been changed in a bunch of ways which go beyond just cleanup – I'm not sure all the changes are correct.

2024-03-01 15:27 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> -    ax5 = plt.subplot(gs[0:2, 2])
matplotlib will implicitly change the current axis, so you do have to create it, but (at least in the past) methods like `some_axis.scatter` are subtly different to `plt.scatter` – I'm not sure if they've made those differences disappear, but I'd be hesitant to make this change without robust testing of the plotting. Do the results look the same?

2024-03-01 16:14 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
I can undo my latest changes in spectral_estimates.py and create a new PR with those changes.

2024-03-01 19:02 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        self.stancil_iter_list = spec.create_chunk_boundaries(
Removed this changes in last commit. This should be part of another PR.

2024-03-01 19:02 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        neven = is_even(N)
Fixed `is_not_even `function

2024-03-01 19:02 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    return boundaries
Removed this changes in last commit. This should be part of another PR.

2024-03-01 19:02 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    return boundaries
Removed this changes in last commit. This should be part of another PR.

2024-03-01 19:02 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> -def create_chunk_boundaries_unit_lengths(L_unit, data_limits, ov= None,  iter_flag=True):
Removed this changes in last commit. This should be part of another PR.

2024-03-01 19:03 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/A01b_ALT07_SHNH_variance_tester.py
> +    iter_x = spec.create_chunk_boundaries( Lmeter, [ xx.min(), xx.max()],ov =Lmeter*3/4, iter_flag= False)[1,:]
Removed this changes in last commit. This should be part of another PR.

2024-03-04 13:57 UTC, hollandjg approved these changes
Looks good to me!

2024-03-04 15:57 UTC, kmilo9999 commented
@cpaniaguam one last review on your side?

2024-03-04 18:42 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
>  def get_leaps():
I think this is more an issue for the future.

2024-03-04 18:42 UTC, cpaniaguam requested changes

2024-03-04 18:53 UTC, kmilo9999 commented on pyproject.toml
> +  "astropy >=5.2, <= 6.0.0"
Removing conditional imports to the top of the files make the interpreter loom for those dependencies when running the scripts

2024-03-04 20:31 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +        fitting_args, fitting_kargs = self.fitting_args, self.fitting_kargs
This part of the code requires some rework. I'll create an issue with this. #169

2024-03-04 20:34 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +        self, fitting_args=None, method="emcee", steps=100, verbose=True, **kargs
This class needs to be reviewed - refactorized.

2024-03-04 20:37 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +    def plot_sample(self, **kargs):
Done

2024-03-04 20:40 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +        self.nwalkers = int(var_seeds[0].size * var_seeds[1].size)
Done

2024-03-04 20:40 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +    cost_sqrt = (abs(z - z_model)) ** 2
Done

2024-03-04 20:40 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +        penalties = np.array([(abs(a_0 - pars["alpha"]) ** 2 / a_std**2)])
Done

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +    cost = (abs(z - z_model)) ** 2 / z.std() ** 2
Done

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +        return np.concatenate([cost, prior_weight * penalties])
Done

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +            Tmedian[key + "_std"] = np.nan
file re-formatted

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +
Done

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
>      return abs(T_lat[T_time.argmax()]) > abs(T_lat[T_time.argmin()])
Done

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +        )
Done

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +            print("Seeds: ", self.seeds.shape)
file reformatted

2024-03-04 20:41 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +            raise ValueError("nor proframmed for 3d")
Done

2024-03-04 21:58 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +    )
Done

2024-03-04 21:58 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +    )
Done

2024-03-04 21:58 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +    )
Done

2024-03-04 21:59 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
>  class sample_with_mcmc:
Renamed

2024-03-04 21:59 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +            **kargs,
Done

2024-03-05 20:59 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +            Tmedian[key + "_std"] = np.nan
Sorry , I missed the change. It was about the string format not the file identation

2024-03-05 21:08 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +        return -np.power((x - x0) / sigma, 2.0) / 2.0
Changed.

2024-03-05 21:08 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
I guess. Any change you want me to apply???

2024-03-07 15:44 UTC, cpaniaguam requested changes
Just a couple more easy changes and a suggested issue.

2024-03-07 15:44 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>      def cal_spectrogram(self, data=None, name=None):
```suggestion
    def cal_spectrogram(self, data=None, name="power_spec"):
```

2024-03-07 15:44 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        self.spec_name = "power_spec" if name is None else name
If the previous suggestion is added, this line can be deleted.
```suggestion
        self.spec_name = name
```

2024-03-07 15:44 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> -        # init Lomb scargle object with noise as nummy data ()
This comment seems useful. Keep it?

2024-03-07 15:44 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    def cal_spectrogram(self, x=None, data=None, name=None, dx=1):
```suggestion
    def cal_spectrogram(self, x=None, data=None, name="power_spec", dx=1):
```

2024-03-07 15:44 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        self.spec_name = "power_spec" if name is None else name
```suggestion
        self.spec_name = name
```

2024-03-07 15:44 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
The `WavenumberSpectrogram` and `WavenumberSpectrogramLSEven` seem to have a lot in commom. Issue to refactor at some point in the future?

2024-03-07 15:44 UTC, hollandjg submitted a review, later dismissed
It's a big change, and it looks good to me. Hopefully nothing has gotten through the cracks.

2024-03-07 15:44 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> -    ax5 = plt.subplot(gs[0:2, 2])
The methods appear to be present on the axis! Looks good to me.

2024-03-07 17:07 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    if method is "fftX2":
I changed it manually to `==`

2024-03-07 17:07 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        self.k, self.dk = calc_freq_fft(x_grid, Lpoints)
I reverted this change

2024-03-07 17:10 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>      def cal_spectrogram(self, data=None, name=None):
Done

2024-03-07 17:10 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +    def cal_spectrogram(self, x=None, data=None, name=None, dx=1):
Done

2024-03-07 17:10 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        self.spec_name = "power_spec" if name is None else name
Done

2024-03-07 17:12 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
#188

2024-03-07 17:12 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> -        # init Lomb scargle object with noise as nummy data ()
I added the commented

2024-03-07 17:19 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        self.ov = int(Lpoints / 2) if ov is None else ov
Done. I added the comment

2024-03-07 18:05 UTC, cpaniaguam approved these changes
👍

2024-03-07 18:13 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +            f = df * np.arange(df, N)
So, this statement is repeated all over the script. I changed only one of them

2024-03-07 18:20 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>      returns all need chunk boudaries and center position given L, and ov
It is now

2024-03-07 18:20 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
>          return position_stancil
It is now

2024-03-07 18:25 UTC, kmilo9999 commented
@cpaniaguam I added few changes requested in old conversations. Some of the doesnt seem to be reflected in their respective conversation. Please re-review and approve if you think is ready.

2024-03-07 19:06 UTC, cpaniaguam approved these changes

2024-03-07 19:06 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        self.ov = int(Lpoints / 2) if ov is None else ov
I see it!

2024-03-07 19:19 UTC, hollandjg approved these changes
Great! Let's merge it!

2024-03-07 19:47 UTC, merged