Publish to PYPI using Github CI
brown-ccv/icesat2-tracks pull request #133
Opened 2024-02-26 19:09 UTC by kmilo9999

Added workflow to publish to pip

2024-02-27 20:12 UTC, hollandjg requested changes
Great! I've a couple of suggestions.

2024-02-27 20:12 UTC, hollandjg commented on .github/workflows/publish_pypi.yml
> +        python-version: 3.8
Are we using python 3.11 in the rest of the project? Perhaps we should use the same here.

2024-02-27 20:12 UTC, hollandjg commented on .github/workflows/publish_pypi.yml
> +        python -m twine upload --skip-existing --repository pypi dist/*
If you replace this bit with trusted publishers on PyPI, you can avoid having to deal with tokens https://docs.pypi.org/trusted-publishers/using-a-publisher/ 

There's some more info here: https://intersect-training.org/packaging/09-publishing-citations/index.html

2024-02-27 20:12 UTC, hollandjg commented on .github/workflows/publish_pypi.yml
> +        python -m twine upload --skip-existing --repository pypi dist/*
Maybe set this up initially so it publishes to test-pypi for testing?

2024-02-27 21:35 UTC, kmilo9999 commented on .github/workflows/publish_pypi.yml
> +        python-version: 3.8
Changed to python 3.11

2024-02-27 21:36 UTC, kmilo9999 commented on .github/workflows/publish_pypi.yml
> +        python -m twine upload --skip-existing --repository pypi dist/*
added trusable publishers action

2024-02-27 21:36 UTC, kmilo9999 commented on .github/workflows/publish_pypi.yml
> +        python -m twine upload --skip-existing --repository pypi dist/*
changed to pypi-test

2024-02-28 15:04 UTC, hollandjg approved these changes
Awesome! 🚀

2024-03-01 14:18 UTC, merged