chore: rename as per PEP 8
brown-ccv/icesat2-tracks pull request #189
Opened 2024-03-07 21:01 UTC by cpaniaguam

General module renaming. A few changed files but straightforward to review.

2024-03-07 21:35 UTC, hollandjg commented on pyproject.toml
The project name on line 13 needs updating here too.

2024-03-07 21:36 UTC, hollandjg commented on pyproject.toml
We should also update everywhere where we list python versions – we're probably only compatible with 3.10 upwards now.

2024-03-07 21:38 UTC, hollandjg requested changes
Looks good! Just a couple of changes in the pyproject.toml file

2024-03-11 12:40 UTC, hollandjg approved these changes
Looks good to me!

2024-03-11 12:40 UTC, hollandjg commented on pyproject.toml
> -"Source" = "https://github.com/brown-ccv/icesat2-tracks"
We'll need to rename the repo to make this consistent. New issue for that?

2024-03-11 13:14 UTC, cpaniaguam commented on pyproject.toml
> -"Source" = "https://github.com/brown-ccv/icesat2-tracks"
Sure, I can take care of that!

2024-03-11 13:20 UTC, cpaniaguam commented on pyproject.toml
> -"Source" = "https://github.com/brown-ccv/icesat2-tracks"
#190

2024-03-11 13:42 UTC, merged