Read-Icesat2 as external dependency
brown-ccv/icesat2-tracks pull request #26
Opened 2023-10-12 16:30 UTC by kmilo9999

Removing read-icesat2 from project and add it as external dependency

2023-10-12 21:09 UTC, hollandjg requested changes
Everything here looks good, but would it be good to delete the modules/read-icesat-2 directory and all its contents too?

2023-10-12 21:09 UTC, hollandjg commented on pyproject.toml
> + "piecewise_regression",
looks like there's a change here you weren't expecting to make
```suggestion
  "piecewise_regression",
```

2023-10-17 19:45 UTC, kmilo9999 commented on pyproject.toml
> + "piecewise_regression",
fixed

2023-10-20 17:42 UTC, hollandjg reviewed
This looks neater – a lot of files cleaned up. Just a couple of questions on details of the pyproject.toml and other file at the bottom – looks like there might be changes in here you didn't want to commit.

2023-10-20 17:42 UTC, hollandjg commented on pyproject.toml
> +build-backend = "hatchling.build"
These are the lines you'd need to change for "hatch" – did you want to include those?

2023-10-20 19:26 UTC, kmilo9999 commented on pyproject.toml
> +build-backend = "hatchling.build"
Good catch. I forgot to remove/comment those lines after the tests we did on the project using hatch. I commented these lines for now in the case we get to use hatch

2023-10-20 20:29 UTC, hollandjg commented on pyproject.toml
> +build-backend = "hatchling.build"
It might be cleaner just to revert the changes completely, because if they stay in as comments they make the file more difficult to read and easier to break. If we come back to using hatch, we should just look at the hatch website and get the latest and greatest version of those lines.

2023-10-24 13:34 UTC, hollandjg approved these changes
Looks good!

2023-10-25 13:52 UTC, merged