Refactor config part 1
brown-ccv/icesat2-tracks pull request #29
Opened 2023-10-25 14:08 UTC by kmilo9999

This PR has a lot of changes, and there are more to come. Better if I submit this as a first part.

- Move configuration scripts to `src `folder
- Remove `modules `folder in root folder
- Move repeated code to a separate module
- Tested script `A01b_ALT07_SHNH_variance_tester.py` (step 2)
-

2023-10-25 17:32 UTC, hollandjg requested changes
Hey Camilo, thanks for the PR! I've had a look through it and I have some detailed feedback.
I focused on the `config` part, because that was in the PR headline. 

I'd love to know what the command was you used to test A01b_ALT07_SHNH_variance_tester.py, so I can test it too.

Overall feedback: 
- Config: I think the config is the key next piece of the puzzle, so I think this being the next PR is great. 
  - One key quick win would be to make the paths relative to the current working directory, and add in a way to load the JSON file from the config directory without it needing a particular path. 
  - At the moment, the paths can't work on my machine.
  - This would solve one of the major requirements for the whole project  – can run anywhere – in one go.
- Other movements of files: It would be easier for me to review if you did just one bunch of related changes in one PR – this feels like two or three PRs rolled up into one (which you acknowledge in the PR description). Splitting the PRs along those lines would make it easier for me to review.

I'm happy to chat through any and all of this whenever!

Thanks!

2023-10-25 17:32 UTC, hollandjg commented on analysis_db/A01b_ALT07_SHNH_variance_tester.py
> +sys.path.insert(0, "./modules/ICEsat2_SI_tools")
This shouldn't be needed any more – everything which is in `src` when you do your `pip install` or `poetry install` or `pdm install` will automatically be on the path.

2023-10-25 17:32 UTC, hollandjg commented on analysis_db/A01b_ALT07_SHNH_variance_tester.py
Did you mean to make any modifications to this file? Doesn't seem to be related to the other things you were modifying.

2023-10-25 17:32 UTC, hollandjg commented on config/config.json
> +          "base": "/mnt/c/Projects/Github/icesat2-tracks/"
These paths don't work for me, but see below in config for my comments on this block!

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/__init__.py
isn't ICESat2_si_tools a package we're going to import? It might not need to add an __init__ file at all, especially if the original doesn't have one.

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/A01b_ALT07_SHNH_variance_tester.py
This file looks to be duplicated, rather than moved. Did you make any other changes to it?

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/__init__.py
I'm not sure you need to add a version to this – that's only really relevant for the whole package.

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +mconfig=utils.json_load('config','/mnt/c/Projects/Github/icesat2-tracks/config/')
This path doesn't work for me. Can we load the `./config` from the same directory as *this* file using something like `pathlib.Path(pathlib.Path(__file__).parent, "./config")`

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +#         return cls._instance
Is it sensible just to delete this? It's been moved elsewhere, and if we leave it here it just makes the file less readable.

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/__init__.py
> +__version__ = "0.0.0"
```suggestion
"""Main analysis scripts for the icesat2_tracks package"""
```

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +my_function()
Might want to leave a TODO to delete this once we're done. We could also just do a simple print at the bottom of the file, without declaring a function for it.

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/config/__init__.py
> +__version__ = "0.0.0"
I don't think we need a __version__ here – maybe a docstring for the subpackage
```suggestion
"""Configuration parameters for the icesat2_tracks package"""
```

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/config/config_instance.py
> +        return cls._instance
I don't understand what this is doing. Can we make this simpler? Maybe we make everything which should be on the `icesat2_confi` object (which I think is everything from the 2021_iceSAT2_startup.py, right) into a module, and we just import that? So all you have to do is `from icesat2_tracks import config` and you have your fully setup config object?

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/local_modules/__init__.py
> +__version__ = "0.0.0"
This also doesn't need a \_\_version\_\_
```suggestion
"""Plotting tools for the icesat2_tracks package"""
```

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +#from Chess import <class-name>
Looks like a stray comment here
```suggestion
```

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/local_modules/__init__.py
This directory looks to be primarily plotting tools – how about we give it a name like `src/icesat2_tracks/plot` rather than `local_modules`.

2023-10-25 17:32 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +from . import m_tools_ph3 as MT
You could make this an absolute import to be sure you're getting the right thing.
```suggestion
from icesat2_tracks.plot import m_tools_ph3 as MT
```

2023-10-25 17:32 UTC, hollandjg commented on config/config.json
Did you mean to modify or move this file? Looks like you've copied it into `src/icesat2_tracks/config` rather than moving it.

2023-10-25 19:45 UTC, mochell commented on src/icesat2_tracks/config/utils.py
> +    return data
It does. Currently, each file processing file uses this to loads track specific configs

2023-10-25 19:47 UTC, mochell commented on src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
`ICEsat2_SI_tools` is different then `read_ICESat-2`. The tools contain nearly all core functions needed

2023-10-25 19:52 UTC, mochell commented on analysis_db/A01b_ALT07_SHNH_variance_tester.py
This file is not needed anymore with the new sliderule input, see PR #28 . We may need some functions from this later, but that will then be part of B01_SL_load_ ...

2023-10-30 13:42 UTC, kmilo9999 commented on src/icesat2_tracks/config/config.json
> +          "base": "/mnt/c/Projects/Github/icesat2-tracks/"
This folders are not in the repo (except config). We would have to create them at runtime if they dont exist.

2023-10-30 13:53 UTC, kmilo9999 commented on analysis_db/A01b_ALT07_SHNH_variance_tester.py
> +sys.path.insert(0, "./modules/ICEsat2_SI_tools")
This file needed to be removed from the repo. I dont know why it got in the PR as "modified". I'll remove it.

2023-10-30 13:55 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/__init__.py
The one imported is [read-ICESat-2](https://github.com/brown-ccv/read-ICESat-2).

2023-10-30 13:56 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/A01b_ALT07_SHNH_variance_tester.py
This file is gonna be removed due to the new pipeline.

2023-10-30 13:58 UTC, kmilo9999 commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +#         return cls._instance
I'll delete those lines.

2023-10-30 14:01 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/__init__.py
> +__version__ = "0.0.0"
ok, I'll change it. I just thought the version comment was mandatory on all `__init__.py `files

2023-10-30 14:02 UTC, kmilo9999 commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +my_function()
I'll remove it

2023-10-30 14:02 UTC, kmilo9999 commented on src/icesat2_tracks/config/__init__.py
> +__version__ = "0.0.0"
Again, ok I'll change it. I just thought the version comment was mandatory on all __init__.py files

2023-10-30 14:03 UTC, kmilo9999 commented on src/icesat2_tracks/config/config_instance.py
> +        return cls._instance
I'll remove this file as well. It got mixed in the PR. We dont need it.

2023-10-30 14:04 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +#from Chess import <class-name>
I'll remove it

2023-10-30 14:19 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/__init__.py
Good catch, I named it `local_modules `because they were in the `modules `folder of the original repo. There are 2 issues:
- There is already a `plot ` folder that needs to be created inside the repo in order to run the pipeline
- I think the `plot ` is too general for what all those scripts do. 

We can just rename it as  `plot_tools`, or `measurement_tools `or `mapping_tools`.

2023-10-30 14:23 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +from . import m_tools_ph3 as MT
It's a file that needs to import from another file in the same folder. I dont see why we should use the absolute import.

2023-10-31 15:33 UTC, kmilo9999 commented on src/icesat2_tracks/config/config.json
> +          "base": "/mnt/c/Projects/Github/icesat2-tracks/"
Keep the folder creation script and remove the workspace root folder.

2023-10-31 15:34 UTC, kmilo9999 commented on src/icesat2_tracks/config/utils.py
> +    return data
We dont need this.  Momme already centralized all his utility functions

2023-10-31 15:43 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
Review on  #30

2023-10-31 15:44 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/__init__.py
#30

2023-10-31 15:45 UTC, kmilo9999 commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +mconfig=utils.json_load('config','/mnt/c/Projects/Github/icesat2-tracks/config/')
First comment

2023-10-31 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/__init__.py
> +__version__ = "0.0.0"
Init files will contain a `docstring `describing what the modules do.

2023-10-31 15:54 UTC, kmilo9999 commented on analysis_db/A01b_ALT07_SHNH_variance_tester.py
> +sys.path.insert(0, "./modules/ICEsat2_SI_tools")
leave like it is right now.

2023-10-31 15:55 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/__init__.py
#31

2023-10-31 16:00 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +from . import m_tools_ph3 as MT
Future discuss if we need to keep these relative paths. It might break in the future when auto test are included

2023-10-31 16:01 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +from . import m_tools_ph3 as MT
#32

2023-10-31 16:01 UTC, kmilo9999 commented on config/config.json
I'll delete it.

2023-11-06 16:35 UTC, kmilo9999 commented
@hollandjg I applied changes in this PR according to what we talked in the last meeting. It seems like a big PR , but most of the files where moved from the root to the src folder.

2023-11-06 16:48 UTC, hollandjg requested changes
This is looking better and better! I've looked over the changes – there are a couple of typos and one place you could use a simpler syntax. Getting closer!

2023-11-06 16:48 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/A01b_ALT07_SHNH_variance_tester.py
> +from icesat2_tracks.config import IceSAT2_startup as config
Maybe import `mconfig` directly? – Then you don't need to change any of the code which uses it – it would be a drop-in replacement.
```suggestion
from icesat2_tracks.config.IceSAT2_startup import mconfig
```

2023-11-06 16:48 UTC, hollandjg commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +xr.set_options(display_width=80, display_style='text')
Was uncommenting this intentional?

2023-11-06 16:48 UTC, hollandjg commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +for folder_name, folder_path  in mconfig["paths"].items():
Stray double space:
```suggestion
for folder_name, folder_path in mconfig["paths"].items():
```

2023-11-06 16:48 UTC, hollandjg commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +          os.mkdir(full_path)
You could make this shorter and more robust: 
```suggestion
    pathlib.Path(full_path).mkdir(exist_ok=True)
```

2023-11-06 16:48 UTC, hollandjg commented on src/icesat2_tracks/config/__init__.py
> +"Configuration file containing project paths"
Docstrings are usually triple-quoted:
```suggestion
"""Configuration file containing project paths"""
```

2023-11-06 16:48 UTC, hollandjg commented on src/icesat2_tracks/local_modules/__init__.py
> +"Utiliy funtions to manage parameters to plot results"
```suggestion
"""Utility functions to manage parameters to plot results"""
```

2023-11-06 17:44 UTC, kmilo9999 commented on src/icesat2_tracks/config/IceSAT2_startup.py
> +xr.set_options(display_width=80, display_style='text')
That's the only line in the file using that module. Whether the line stays or the module is removed.

2023-11-07 14:48 UTC, hollandjg approved these changes
Great!

2023-11-07 14:48 UTC, merged