Integrate first step
brown-ccv/icesat2-tracks pull request #35
Opened 2023-11-08 20:43 UTC by kmilo9999

- Moved B01_SL_load_single_file.py to src package folder
- Added necessary modules to work with the new config set up
- Fixed variable nomenclature

2023-11-08 21:38 UTC, cpaniaguam requested changes
I guess we can start cleaning up the files a bit. If you like, consider hitting them with a formatter (black maybe?). Or even better, add pre-commit hooks? Here is a sample one which might do more than we need right now (type checking and stuff like that.) https://github.com/lnccbrown/HSSM/blob/main/.pre-commit-config.yaml Tha

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> +#import io as io_local
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> +    #plt.ylim(0, 20)
```suggestion
    plt.ylabel('segment std log(m)')
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> +    #plt.ylim(0, 20)
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> +## plot track stats basics for sliderules ATL06 output
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
> +        #print(point['lat'], point['x_atc'])
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
>          #print('descending')
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +#import spicke_remover
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +#track_name = ID['tracks']['ATL03'][0] +'.h5'
```suggestion
# Select region and retrive batch of tracks
track_name, batch_key, ID_flag = io.init_from_input(sys.argv) # loads standard experiment
plot_flag = True
hemis = batch_key.split('_')[0]

save_path  = mconfig['paths']['work'] +'/'+batch_key+'/B01_regrid/'
MT.mkdirs_r(save_path)

save_path_json  = mconfig['paths']['work'] +'/'+ batch_key +'/A01b_ID/'
MT.mkdirs_r(save_path_json)

ATL03_track_name = 'ATL03_'+track_name+'.h5'
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +#imp.reload(beam_stats)
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    #table_data = copy.copy(B01b_atl06_native)
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +                        #'spot':'beam',
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +# add spike remover
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +
```suggestion
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +#DD['pars']['start']['delta_time'] = str(table_data.index[start_pos])
```suggestion
},
'end': {'longitude': table_data.lons[end_pos], 'latitude': table_data.lats[end_pos]
, 'seg_dist_x': float(table_data.x[end_pos])
, 'delta_time': datetime.datetime.timestamp(table_time[end_pos])
},
    }
```

2023-11-08 21:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +
```suggestion
```

2023-11-10 15:00 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> +    #plt.ylim(0, 20)
done

2023-11-10 16:12 UTC, cpaniaguam requested changes
Couple more cleanups suggested..

2023-11-10 16:12 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
>      # last_time = cGPS.convert_GPS_time(last_point['delta_time'], last_point['rgt'], last_point['orbit_number'])
Can these be deleted?
```suggestion
```

2023-11-10 16:12 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
> +#import io as io_local
Delete this one?

2023-11-10 16:12 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +gdf = sct.correct_and_remove_height(gdf, maximum_height)#.plot(markersize=0.2)
```suggestion
gdf = sct.correct_and_remove_height(gdf, maximum_height)
```

2023-11-10 16:12 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +        # this is not tested
Seeing comments like this one is a bit unsettling to me. Do we know if this has been tested?

2023-11-10 16:12 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    plt.close()
```suggestion
    plt.title(track_name +  '\nascending =' + str(sct.ascending_test_distance(gdf)) , loc ='left')
    M.save_anyfig(plt.gcf(), path = plot_path  ,name = 'B01_track.png')
    plt.close()
```

2023-11-10 20:24 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
>      # last_time = cGPS.convert_GPS_time(last_point['delta_time'], last_point['rgt'], last_point['orbit_number'])
@mochell what you think?

2023-11-10 20:25 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +        # this is not tested
It works on my side. @mochell any thoughts ?

2023-11-14 14:35 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +        # this is not tested
I think we need to live with the unsettling feeling. This should be fine.

2023-11-14 14:38 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
> +    test if the track is ascending or descending based on 'x_atc' column
This is the column name we get from sliderule.

2023-11-14 17:50 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
>      # last_time = cGPS.convert_GPS_time(last_point['delta_time'], last_point['rgt'], last_point['orbit_number'])
Commented code removed

2023-11-14 17:51 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +# %%
removed these marks from this specific file.

2023-11-14 20:42 UTC, hollandjg approved these changes
Rocker🚀

2023-11-14 21:10 UTC, merged