Run test on step 1
brown-ccv/icesat2-tracks pull request #41
Opened 2023-11-15 16:40 UTC by kmilo9999

- Workflow to test step 1 integration

2023-11-17 19:06 UTC, hollandjg requested changes
Hi Camilo,
it looks like this isn't passing, because it's missing the `config.json file. You'll need to update the pyproject.toml line 154:
```toml 
[tool.setuptools]
# If there are data files included in your packages that need to be
# installed, specify them here.
# TODO: ADD ANY DATA FILES WE WANT TO HAVE
package-data = {"icesat2_tracks" = ["config/*.json"]}
```

2023-11-28 16:15 UTC, hollandjg approved these changes
Looks good to me!

2023-11-28 21:36 UTC, cpaniaguam reviewed
Added a couple of clarifying questions and comments (that are most likely to be useful later?).

2023-11-28 21:36 UTC, cpaniaguam commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        version: ['3.9']
Can other versions be added here? I think some code needed python 3.10 or 3.11 but I could be wrong on this.

2023-11-28 21:36 UTC, cpaniaguam commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: sudo apt update && sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
Why was this needed? Maybe add a comment?

2023-11-28 21:36 UTC, cpaniaguam commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: python src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py 20190502052058_05180312_005_01 SH_testSLsinglefile2 True
Note to self: I guess this might be a command to add to CLI.

2023-11-28 21:36 UTC, cpaniaguam commented on src/icesat2_tracks/config/color_def.ai
What is this file for? Maybe some comments can be added at the top to describe its purpose?

2023-11-28 21:36 UTC, cpaniaguam commented on src/icesat2_tracks/config/color_def.ase
Is this file needed to set up the CI?

2023-11-28 21:36 UTC, cpaniaguam commented on src/icesat2_tracks/config/generate_colors.py
> +    print(i['name'] + '  ' + str(i['data']['values']))
```suggestion
```

I guess we are not refactoring stuff yet, but this print statement can probably be deleted and use a dict comprehension to populate `B`.

2023-11-28 21:36 UTC, cpaniaguam commented on src/icesat2_tracks/config/generate_colors.py
> +B['rels']=rels
This can probably be refactored as well but I guess we'll get that later.

2023-11-28 21:36 UTC, cpaniaguam commented on pyproject.toml
Can the template generic comments be removed now that the project is (completely?) set up?

2023-11-28 21:44 UTC, merged