Integrate step 2
brown-ccv/icesat2-tracks pull request #44
Opened 2023-12-06 21:04 UTC by kmilo9999

- Modified `m_spectrum_ph3.py` and `ICEsat2_SI_tools/generalized_FT.py` to integrate the pipeline's step 2 to the current folder structure and packaging configuration

2023-12-11 16:10 UTC, cpaniaguam approved these changes
I think this is good! We can do some cleanups later.

2023-12-11 16:29 UTC, hollandjg requested changes
There seems to be an install problem here!

2023-12-11 16:29 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  #%matplotlib inline
Did we say we'd remove comments like this? I think we did in the first step.

2023-12-11 16:29 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
You might also want to remove the cell markers
`# %%`
... for consistency with the first step.

2023-12-12 14:40 UTC, kmilo9999 commented on pyproject.toml
@kmilo9999 check when tables is being used.

2023-12-12 20:59 UTC, kmilo9999 commented on .github/workflows/test-B01_SL_load_single_file.yml
> +      - name: second step make_spectra
Done

2023-12-12 20:59 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
Done

2023-12-12 21:01 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  #%matplotlib inline
I removed most of those lines with '%'

2023-12-12 21:02 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
Done

2023-12-13 20:23 UTC, kmilo9999 commented on pyproject.toml
@hollandjg This error is because it's not finding HDF5 in your macos. I created a [workflow ](https://github.com/brown-ccv/icesat2-tracks/actions/runs/7187881403) that checks the installation in that system and they seem to work. Have you set the `HDF5_DIR` environmental variable?

@cpaniaguam @hollandjg This is the stack trace of the throw error when the `pytables `dependency is missed.
```
Traceback (most recent call last):
  File "/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py", line 439, in <module>
    MT.save_pandas_table(Pars_optm, save_name+'_params', save_path )
  File "/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/local_modules/m_tools_ph3.py", line 282, in save_pandas_table
    with HDFStore(save_path+'/'+ID+'.h5') as store:
  File "/mnt/c/Projects/Github/icesat2-tracks/venv39/lib/python3.9/site-packages/pandas/io/pytables.py", line 566, in __init__
    tables = import_optional_dependency("tables")
  File "/mnt/c/Projects/Github/icesat2-tracks/venv39/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
```
Basically, when the analysis results are being save to a pandas table,  `pandas ` calls the function :
`import_optional_dependency("tables")`
and that producess the error

2023-12-14 17:31 UTC, cpaniaguam reviewed
Suggested a couple more cleanups before approving and merging.

Also added some comments for future development items.

2023-12-14 17:31 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  # h=hpy()
```suggestion
```

2023-12-14 17:31 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  #track_name, batch_key, test_flag = '20190601094826_09790312_004_01', 'SH_batch01', False
```suggestion
```

2023-12-14 17:31 UTC, cpaniaguam commented on pyproject.toml
> +  "tables"
We might be able to remove this dep if the I/O is optimized in step 2.

2023-12-14 17:31 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  track_name, batch_key, test_flag = io.init_from_input(sys.argv) # loads standard experiment
This might change after the cli is implemented.

2023-12-14 19:50 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  #track_name, batch_key, test_flag = '20190213133330_07190212_004_01', 'SH_batch02', False
Delete?
```suggestion
```

2023-12-14 19:51 UTC, cpaniaguam requested changes
Pointed out a few more lines that can also be deleted.

2023-12-15 15:32 UTC, cpaniaguam requested changes
I am requesting one more deletion of commented code. Other than that I think this is ready to merge!

2023-12-15 15:32 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  #from memory_profiler import profile
Why not delete these too?

2023-12-15 15:32 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  #track_name, batch_key, test_flag = '20190205231558_06030212_004_01', 'SH_batch02', False
I might have missed suggesting removing other commented code, but lines 61-76, 78, 106 could be deleted.

2023-12-15 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  #track_name, batch_key, test_flag = '20190205231558_06030212_004_01', 'SH_batch02', False
I removed all the commented code

2023-12-15 17:03 UTC, cpaniaguam approved these changes
Thanks!

2023-12-15 17:03 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
Clean as a whistle!

2023-12-15 19:26 UTC, hollandjg commented on pyproject.toml
This solves it, but I think it needs to be in the README. I've put in a suggestion in #49 which can be merged into this branch.
- #49

2023-12-15 19:26 UTC, hollandjg commented on pyproject.toml
> +  "tables"
That would be nice.

2023-12-15 19:27 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  track_name, batch_key, test_flag = io.init_from_input(sys.argv) # loads standard experiment
Absolutely!

2023-12-15 19:27 UTC, hollandjg approved these changes
Love it! Just one suggested change in #49

2023-12-15 21:32 UTC, merged