Feature step3 integration
brown-ccv/icesat2-tracks pull request #45
Opened 2023-12-11 19:29 UTC by kmilo9999

- Adding B03_plot_spectra_ov.py to the new packaging structure

2023-12-11 19:31 UTC, kmilo9999 commented
@mochell when I run the command:
`python B03_plot_spectra_ov.py SH_20190502_05180312 SH_testSLsinglefile2 True`
I got a lot of warnings:

 ```
self.fig.savefig(full_name, bbox_inches='tight', format='pdf', dpi=300)
save at:  ./plots//SH/SH_testSLsinglefile2/SH_20190502_05180312/B03_spectra/B03_freq_reconst_x53.pdf
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py:497: RuntimeWarning: All-NaN slice encountered
  dd_max.append(np.nanmax(dd.data))
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py:497: RuntimeWarning: All-NaN slice encountered
  dd_max.append(np.nanmax(dd.data))
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py:497: RuntimeWarning: All-NaN slice encountered
  dd_max.append(np.nanmax(dd.data))
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/local_modules/m_general_ph3.py:149: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.fig.savefig(full_name, bbox_inches='tight', format='pdf', dpi=300)
save at:  ./plots//SH/SH_testSLsinglefile2/SH_20190502_05180312/B03_spectra/B03_freq_reconst_x64.pdf
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py:497: RuntimeWarning: All-NaN slice encountered
  dd_max.append(np.nanmax(dd.data))
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py:497: RuntimeWarning: All-NaN slice encountered
  dd_max.append(np.nanmax(dd.data))
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py:497: RuntimeWarning: All-NaN slice encountered
  dd_max.append(np.nanmax(dd.data))
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py:497: RuntimeWarning: All-NaN slice encountered
  dd_max.append(np.nanmax(dd.data))
/mnt/c/Projects/Github/icesat2-tracks/src/icesat2_tracks/local_modules/m_general_ph3.py:149: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.fig.savefig(full_name, bbox_inches='tight', format='pdf', dpi=300)
save at:  ./plots//SH/SH_testSLsinglefile2/SH_20190502_05180312/B03_spectra/B03_freq_reconst_x75.pdf

```

Any thoughts ?

2024-01-11 16:39 UTC, hollandjg requested changes
This looks good! I've a couple of suggestions and clarifying questions, but nothing major. Thanks, Camilo!

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/config/IceSAT2_startup.py
It think we'll need a new issue to remove the upper-case letter from this file's name, because they don't conform to PEP8. We could rename this file to `startup.py` or similar. But do this later and in one go once the package is cleaned up.

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +import icesat2_tracks.ICEsat2_SI_tools.spectral_estimates as spec
We should probably rename the sub package at some point – could call it just `icesat2_tracks.tools`. Not a change for now though – we could make a new issue for this.

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +)
Another thing for the future – we could refactor lines like these to use `pathlib.Path.join(part1, part2, ...)` – it's a bit more robust. But not a change for now.

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
This looks like you've made the standard modifications at the start of the file, and then run the reformatter. Were there any code changes you had to make to make it work? I can't see them if there are, but if there were any and you'd like a specific review of those, please let me know!

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +"""
The comment should come right at the start of the file, so I'd switch these lines around:
```suggestion
"""
This file open a ICEsat2 track applied filters and corections and returns smoothed photon heights on a regular grid in an .nc file.
This is python 3
"""

import os, sys
```

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> -    k_low_limits =data.k[::10]
I think we should throw a warning here and discuss with @mochell  – `dk` isn't actually used, so I think there's something funky about this function.

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +    f_weight = np.sqrt(9.81 * k_fft) / (2 * np.pi)
Suggestion for a new issue: Perhaps we should replace 9.81 (which is used through this function) with a variable? It'll be the standard gravitational acceleration, so we could call it `g = 9.81` or `gravitational_acceleration = 9.81` and then use that wherever it's used. There might be other places where we have something similar, and perhaps we want to do that everywhere.

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        return wavenumber_spectrogram.mean_spectral_error(
This method seems like it must be broken – `wavenumber_spectrogram` doesn't look to be defined anywhere. Do we use `mean_spectral_error` anywhere?

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> -    k_low_limits =data.k[::10]
Probably make that an issue to handle during the later clean-up – not for now.

2024-01-11 16:39 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
This looks like just a reformatting of the file, and that seems to be good.

There are some commented out bits of code in here, which we could remove, but I think that should be a separate issue (if we don't already have one). There are a couple of places where it looks like methods and functions are defined in a way that they can't possibly work as you'd expect (arguments unused or used variables undefined), but if the code works then we can ignore these for now and just make a note for the future.

2024-01-11 16:39 UTC, hollandjg commented on .github/workflows/test-B01_SL_load_single_file.yml
> +      - name: third step make_spectra
```suggestion
      - name: third step plot_spectra
```

2024-01-11 16:45 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
Remembering to back to the files and do cleanups might be tedious. I don't mind adding a few suggestions to clean up the file right now!

2024-01-11 16:47 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +    f_weight = np.sqrt(9.81 * k_fft) / (2 * np.pi)
I like this suggestion! Is this the kind of thing that could go into a separete module with constants and things like that?

2024-01-11 16:59 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          return Gmean
Maybe this is another thing worth checking with @mochell. The type of the returned objectn of this function is not stable and this requires special handling by the caller of the function. I think it's better to make it return a tuple (or better, a nameptuple) and make the downstream logic simpler. Maybe for a separate issue?

2024-01-11 17:32 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +)
I like this. However, `pathlib.Path.join` is a bit verbose, isn't it? I guess a simpler alias (`joinpath`?) could be defined.

2024-01-11 17:34 UTC, cpaniaguam commented on src/icesat2_tracks/config/IceSAT2_startup.py
>  #matplotlib.use('Agg')
```suggestion
```

2024-01-11 17:36 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
```suggestion
```

2024-01-11 17:37 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # print(PP2)
```suggestion
```

2024-01-11 17:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          # #self.GG['win'] = ( ('eta'), np.insert(self.win, -1, self.win[-1]))
```suggestion
```

2024-01-11 17:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +                # x_mask= (sta <= X) & (X <= ste)
```suggestion
```

2024-01-11 17:38 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +                    ]  # np.append(I['model_error_x'], I['model_error_x'][-1])
```suggestion
                    ] 
```

2024-01-11 17:39 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # model_error_x
```suggestion
```

2024-01-11 17:39 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
```suggestion
```

2024-01-11 17:46 UTC, cpaniaguam commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: python src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py SH_20190502_05180312 SH_testSLsinglefile2 True
```suggestion
        run: python src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py SH_20190502_05180312 SH_testSLsinglefile2 True
   
```

Maybe formatters/pre-commit can be configured to add a new line at the end of files?

2024-01-11 17:48 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +            GSUM += I.where(~np.isnan(I), 0) * I[weight_key]  # .sel(x=GSUM.x)
```suggestion
            GSUM += I.where(~np.isnan(I), 0) * I[weight_key] 
```

2024-01-11 18:02 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +    )
```suggestion
try:
    k_max = Gmean.k[Gmean.isel(x=slice(0, 5)).mean("x").argmax().data].data
except:
    k_max = Gmean.k[Gmean.isel(x=slice(0, 20)).mean("x").argmax().data].data

k_max_range = (k_max * 0.75, k_max * 1, k_max * 1.25)
```

`Gmean.k[Gmean.isel(x=slice(0, 5)).mean("x").argmax().data].data` could also be moved to a function but this is simpler for now.

2024-01-11 18:08 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +
The rest of the file deals with plotting. I think it's sensible to move these to another file/function to abstract away complexity. For a separate issue?

2024-01-11 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/config/IceSAT2_startup.py
>  #matplotlib.use('Agg')
```
###
#   THIS FILE IS A LOCAL FILE
#   it is not maintained via git, it contains configs specific to the machine
###
#os.environ["DISPLAY"] = "localhost:10.0"
# 14, 16,  work
#standart libraries:
```

Has anyone given some thought to this? Should this be moved to configs?

2024-01-11 20:12 UTC, cpaniaguam requested changes
Added a number of cleanups and simple refactorings. I will open a separate PR to clean up one of the files (`icesat2_tracks/config/IceSAT2_startup.py`) with a lot of commented code.

2024-01-11 20:12 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # self.R      = np.diag(  data_uncertainty) #Noise Prior N x N
```suggestion
```

2024-01-11 20:12 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          # else:
```suggestion
```

2024-01-11 20:12 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # self.ydata_star        = self.ydata
```suggestion
```

2024-01-11 20:12 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>  class generalized_Fourier(object):
```suggestion
class generalized_Fourier:
```

2024-01-11 20:12 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>  class get_prior_spec(object):
```suggestion
class get_prior_spec:
```

2024-01-12 14:31 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
I cleaned and formatted the file

2024-01-12 14:33 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +import os, sys
`os` is  not being used. I removed it

2024-01-12 14:42 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +)
#62

2024-01-12 16:51 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +import icesat2_tracks.ICEsat2_SI_tools.spectral_estimates as spec
#57

2024-01-12 17:15 UTC, kmilo9999 commented on src/icesat2_tracks/config/IceSAT2_startup.py
#56

2024-01-12 20:12 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +"""
`os` wasnt used in the file

2024-01-12 20:17 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> -    k_low_limits =data.k[::10]
This `rebin` is used in a file that is not used in the pipeline

2024-01-12 20:18 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> -    k_low_limits =data.k[::10]
This `rebin ` function is used in a file that is not used in the pipeline. We could delete it.

2024-01-12 20:19 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +    f_weight = np.sqrt(9.81 * k_fft) / (2 * np.pi)
#65

2024-01-12 20:22 UTC, kmilo9999 commented on .github/workflows/test-B01_SL_load_single_file.yml
> +      - name: third step make_spectra
done

2024-01-12 20:24 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          return Gmean
I dont see `rebin` used in the files running the pipeline

2024-01-12 20:27 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
Done

2024-01-12 20:27 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +                    ]  # np.append(I['model_error_x'], I['model_error_x'][-1])
done

2024-01-12 20:28 UTC, kmilo9999 commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: python src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py SH_20190502_05180312 SH_testSLsinglefile2 True
let me add the formatter in another PR

2024-01-12 20:29 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +            GSUM += I.where(~np.isnan(I), 0) * I[weight_key]  # .sel(x=GSUM.x)
done

2024-01-12 20:29 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +    )
I applied your change

2024-01-12 20:30 UTC, cpaniaguam commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: python src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py SH_20190502_05180312 SH_testSLsinglefile2 True
This might be a local setting, though.

2024-01-12 20:30 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>      # weight = weight *10+ weight.max()* 0.005 # add pemnalty floor
done

2024-01-12 20:31 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # weight = weight *1+ weight.max()* 0.1 # add pemnalty floor
done

2024-01-12 20:31 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # Spec_fft.data[np.isnan(Spec_fft.data)] = 0
done

2024-01-12 20:31 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # self.R      = np.diag(  data_uncertainty) #Noise Prior N x N
done

2024-01-12 20:31 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        # self.ydata_star        = self.ydata
done!

2024-01-12 20:33 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>  class get_prior_spec(object):
Done

2024-01-12 20:34 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>  class generalized_Fourier(object):
#64

2024-01-12 20:36 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          # else:
I cleaned the file

2024-01-16 15:06 UTC, hollandjg reviewed
Great! Once Carlos' comments are handled, this looks good to me!

2024-01-16 15:06 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +)
There's an argument for both – `joinpath` would be shorter, but people will immediately recognize `pathlib.Path.join` (or `from pathlib import Path` then `Path.join`) and won't have to look back at the import statement to understand what it's doing.

2024-01-16 15:06 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        return wavenumber_spectrogram.mean_spectral_error(
ah, that'll be it - one of the imports handled by the old scripts which ran at the start of the file. Good catch, @cpaniaguam !

2024-01-16 15:06 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          return Gmean
I like the namedtuple idea! But a deletion is even better, if we don't need it!

2024-01-16 17:59 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          return Gmean
What about returning the values `Gmean,none `. I can modify the _only_ line in the whole project that needs this function to retrieve two values?

2024-01-16 19:23 UTC, kmilo9999 commented on src/icesat2_tracks/config/IceSAT2_startup.py
>  #matplotlib.use('Agg')
#67

2024-01-16 19:26 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +    return eta_1
@kmilo9999 Where do you stand on [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)?

2024-01-16 19:26 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
>          return Gmean
If the caller of this function only needs one value, wouldn't it be better to make the function return `Gmean` only and make the required change?

2024-01-16 21:43 UTC, cpaniaguam commented on analyis_publish/PB05_define_angle.py
Folder added to .gitignore.

2024-01-16 21:43 UTC, cpaniaguam commented on analyis_publish/PB05_define_angle_supl.py
Folder added to .gitignore.

2024-01-16 21:44 UTC, cpaniaguam commented on analysis/SB04_2d_wavefield_emulator.py
Folder added to .gitignore.

2024-01-16 21:46 UTC, cpaniaguam commented on analysis_db/B05_define_angle.py
Folder added to .gitignore.

2024-01-16 21:50 UTC, cpaniaguam approved these changes
Thanks!

And congrats!!

2024-01-16 21:51 UTC, merged

2024-01-19 22:51 UTC, mochell commented
> @mochell when I run the command: `python B03_plot_spectra_ov.py SH_20190502_05180312 SH_testSLsinglefile2 True` I got a lot of warnings:
> 
..
>
> Any thoughts ?

I think its just a bunch of warmings in cases when there is no data in the slice. should be solvable with an if statement..

2024-01-19 22:56 UTC, mochell commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +
yes. make a method out of it

2024-01-19 22:56 UTC, mochell commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +    return eta_1
if xscale is not in the function then it will be plt.xticklabel i assume

2024-01-19 22:56 UTC, mochell commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +        return wavenumber_spectrogram.mean_spectral_error(
@cpaniaguam  is right!