add some instructions for HDF5-dependency
brown-ccv/icesat2-tracks pull request #49
Opened 2023-12-15 19:25 UTC by hollandjg

2023-12-15 19:55 UTC, cpaniaguam commented on README.md
> +- HDF5 (e.g. from `brew install hdf5` on macOS)
Is this a _true_ prerequisite? I tested without having to explicitly install hdf5 and it worked fine.

2023-12-15 21:32 UTC, kmilo9999 approved these changes

2023-12-15 21:32 UTC, kmilo9999 commented on README.md
> +- HDF5 (e.g. from `brew install hdf5` on macOS)
I believe it is necessary. Maybe you already had hdf5 installed from a previous project or library.

2024-01-10 20:13 UTC, cpaniaguam requested changes
Suggesting adding a line for consistency. Thanks!

2024-01-10 20:13 UTC, cpaniaguam commented on README.md
> +  > You may need to set the value of the `HDF5_DIR` environment variable to install some of the dependencies, especially when installing on macOS. For Apple Silicon (M-Series) CPUs:
```suggestion
  > You may need to set the value of the `HDF5_DIR` environment variable to install some of the dependencies, especially when installing on macOS.
  
For Apple Silicon (M-Series) CPUs:
```

2024-01-11 16:20 UTC, cpaniaguam approved these changes
🚀

2024-01-11 16:41 UTC, merged