Feature step5 integration
brown-ccv/icesat2-tracks pull request #51
Opened 2023-12-28 23:03 UTC by kmilo9999

- Add step5 `analysis_db/B04_angle.py`
- Updated `ICEsat2_SI_tools/generalized_FT.py` and `ICEsat2_SI_tools/sliderule_converter_tools.py` to fix integration issues
- Cleaned and formatted files

2024-01-12 15:10 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
Modified in #45. Wait for merge?

2024-01-12 15:13 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
Yes!!

2024-01-24 16:53 UTC, cpaniaguam requested changes
I noted some changes that seem experimental. Others seem a bit mysterious (`dist` => `x`). Maybe some comments could be added to reveal the motivation behind them.

2024-01-24 16:53 UTC, cpaniaguam commented on pyproject.toml
> +  "siphon==0.9"
Should the versions be kept pinned? I hear it might be detrimental if the package is used with other tools with the same dependencies. Maybe use `>=` for the lower bound and cap with `<` for the upper bound.
```
dependencies = [ # Optional
  "piecewise_regression>=1.3.0, <2.0.0",
  "numba >=0.58.1, <1.0.0",
  "xarray >=2024.1.0", # this doesn't look like semmatic versioning
  "mpi4py >=3.1.4, <4.0.0",
  "numpy >=1.26.3, <2.0.0",
  "icesat2-toolkit >=1.0.0.22, <2.0.0",
  "pandas >=2.2.0, <3.0.0",
  "geopandas >=0.14.2, <1.0.0",
  "sliderule >=4.2.3, <5.0.0",
  "ipyleaflet >=0.18.1, <0.19.0",
  "lmfit >=1.2.2, <2.0.0",
  "tables >=3.9.2, <4.0.0",
  "emcee >=3.1.4, <4.0.0",
  "netCDF4 >=1.6.5, <2.0.0",
  "siphon >=0.9, <1.0.0"
]
```

2024-01-24 16:53 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +            sys.stdout = old_stdout
I can see how this can be useful, but it seems like it's not used at all (?).

2024-01-24 16:53 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
TODO: use pathlib.Path

2024-01-24 16:53 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +Prior
```suggestion
```

2024-01-24 16:53 UTC, cpaniaguam commented on pyproject.toml
> +  "siphon==0.9"
Also, I see `h5py` being imported in `B04_angle.py`. Should it be added above?

2024-01-24 16:53 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    lats_no_gaps = linear_gap_fill(Gd_cut, "x", "lats")
Curious about the change from `dist` => `x`.

2024-01-24 18:09 UTC, kmilo9999 commented on pyproject.toml
> +  "siphon==0.9"
The icesat2-toolkit package has h5py as a dependency.

2024-01-24 18:23 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    lats_no_gaps = linear_gap_fill(Gd_cut, "x", "lats")
My guess is that 'dist' is the convention defined by sliderule. 'x' was the name of that index in the previous pipeline.

2024-01-24 18:24 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +            sys.stdout = old_stdout
It's not used at least in this file. I'll remove it.

2024-01-24 18:25 UTC, kmilo9999 commented on pyproject.toml
> +  "siphon==0.9"
how did you come up with those range of versions?

2024-01-24 18:25 UTC, kmilo9999 commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: pip install --upgrade --editable ".[dev]"
done!

2024-01-24 18:26 UTC, kmilo9999 commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        #run: brew install open-mpi
I removed it

2024-01-24 19:15 UTC, cpaniaguam commented on pyproject.toml
> +  "siphon==0.9"
@mochell When a package uses [semantic versioning](https://semver.org/#semantic-versioning-200), minor releases (going from v3.1 to v3.2, say) don't add any breaking changes. This is called backward compatibility. So code written with version v3.1 of a package should run with any v3.x, x > 1, of the same package.

2024-01-24 19:18 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    lats_no_gaps = linear_gap_fill(Gd_cut, "x", "lats")
That is a breaking change on their part!

2024-01-24 19:52 UTC, kmilo9999 commented on pyproject.toml
> +  "siphon==0.9"
@cpaniaguam The dependencies version range failed. I rolled back to specific versions.

2024-01-24 20:00 UTC, cpaniaguam commented on pyproject.toml
> +  "siphon==0.9"
@kmilo9999 That is strange. What happened?

2024-01-24 20:24 UTC, kmilo9999 commented on pyproject.toml
> +  "siphon==0.9"
It downloaded an updated icesat2-toolkit version (1.3.0) that doesnt seem to have the h5py dependency. I included in the list of our dependencies in the toml file

2024-01-24 21:26 UTC, cpaniaguam requested changes
A couple more cleanups suggested!

2024-01-24 21:26 UTC, cpaniaguam commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: pip install --upgrade --editable ".[dev]"
```suggestion
        run: pip install .
```

2024-01-24 21:32 UTC, mochell commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    lats_no_gaps = linear_gap_fill(Gd_cut, "x", "lats")
It should be the same but I don't garantie..

2024-01-24 23:16 UTC, kmilo9999 commented on .github/workflows/test-B01_SL_load_single_file.yml
> +        run: pip install --upgrade --editable ".[dev]"
Done!

2024-01-26 15:33 UTC, cpaniaguam requested changes
Happy to see this passing!

I have some general comments and questions, two suggestions for issues I've seen elsewhere in the package, and a couple suggested changes.

2024-01-26 15:33 UTC, cpaniaguam commented on angle_optimizer.patch
What is this file for? Its extension is kind of confusing.

2024-01-26 15:33 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +                        nwalkers=self.nwalkers, steps=steps, pos= self.seeds,nan_policy='omit' , **kargs)
Is there something still left to do here? Otherwise, the `'TODO'` part of the comment could be removed if the change is going to be kept.

2024-01-26 15:33 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +from scipy.ndimage.measurements import label
I think this import throws a deprecation warning.
```suggestion
from scipy.ndimage import label
```
Maybe an issue should be created as I've seen this elsewhere in the package.

2024-01-26 15:33 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +imp.reload(spec)
Lines with `imp.reload` and its corresponding import statements can be removed. `imp` or its successor [`importlib`](https://docs.python.org/3/library/importlib.html#:~:text=importlib.reload(module)) are modules people use during development, not for production code.

There are many instances where `imp` is used in the package. Maybe for another issue?

2024-01-26 15:33 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey = "h_mean"
L160 should go outside (before) of the for loop here.

2024-01-26 15:33 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey = "h_mean"
Clarifying question for me: why the change `"heights_c_weighted_mean"` => `"h_mean"`?

Another sliderule breaking change perhaps?

2024-01-26 15:33 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey_sigma = "h_sigma"
Like the other `hkey` definition above, these are not changing and should go outside of the for loop.

2024-01-26 16:06 UTC, kmilo9999 commented on angle_optimizer.patch
My idea was to patch the file it makes step5 crash. This file has the instruction that changes the specific line that causes the error. But it seems patching the file didnt work either. I'm removing it, but leaving a comment in the `angle_optimizer.py` file mentioning how we solved this issue.

2024-01-26 16:07 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +                        nwalkers=self.nwalkers, steps=steps, pos= self.seeds,nan_policy='omit' , **kargs)
This line is the one throwing the error. The TODO comment is just to remind us that something needs to be done here

2024-01-26 16:11 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +imp.reload(spec)
#84

2024-01-26 16:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey = "h_mean"
@mochell  any thoughts ? :point_up:

2024-01-26 16:18 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey_sigma = "h_sigma"
@mochell any thoughts ? ☝️

2024-01-26 16:19 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey_sigma = "h_sigma"
I agree, we can move these lines outside the loop.

2024-01-26 16:21 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +from scipy.ndimage.measurements import label
done!

2024-01-26 16:52 UTC, cpaniaguam requested changes
I noted a change that was undone (docstring at the top) and I saw a constant being defined in a for loop.

2024-01-26 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
>  """
In a comment in a previous PR John pointed out that it's better to put module docstrings at the top. They serve as module metadata. For example, `help(mymodule)` will print such a docstring. Note that this was the case in the previous commit.

```suggestion
"""
This file open a ICEsat2 track applied filters and corections and returns smoothed photon heights on a regular grid in an .nc file.
This is python 3
"""

import sys
```

2024-01-26 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +)
If we are going to explicitly list deps in files, we should probably get rid of imports like this one.
```suggestion
import matplotlib.pyplot as plt
from icesat2_tracks.config.IceSAT2_startup import mconfig
```

2024-01-26 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey = "h_mean"
> L160 should go outside (before) of the for loop here.

@kmilo9999 What do you think of this change?

If this change is made, the other line, L191, where `hkey` is redefined with the same value can be deleted.

2024-01-26 18:05 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey = "h_mean"
I agree.

2024-01-26 18:10 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    hkey = "h_mean"
The `hkey` is being redefined in line 188 with the same value. I'm removing it from the loop

2024-01-27 03:39 UTC, cpaniaguam approved these changes
🍻

2024-01-29 14:27 UTC, merged