Feature step6 integration
brown-ccv/icesat2-tracks pull request #52
Opened 2024-01-03 20:54 UTC by kmilo9999

- Added file analysis_db/B05_define_angle.py for step 6
- Cleaned code
- Formatted file

2024-01-12 16:19 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
In #51 there is a file named `B04_angle.py`. Should the file at hand  be renamed in that format (no extra `define_`)? Should the other file be renamed to fit the format in this file? @kmilo9999 @hollandjg @mochell

2024-01-19 22:48 UTC, mochell commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
Im not sure what you mean. you want to call it B04_define_angle.py ?

2024-01-20 01:27 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
Yes, just to have a uniform naming convention and make things a bit more intuitive and predictable.

2024-01-29 18:25 UTC, cpaniaguam submitted a review, later dismissed
B05_define_angle needs to be cleaned up. I'll do this when the file is added to the cli.

2024-01-29 19:01 UTC, hollandjg requested changes
Please could you delete the old version of the file so we can see the diff in the GitHub files view? Thanks!

2024-01-29 19:01 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
Is there a more descriptive name we could use? Perhaps an extra verb in the name for B04 so you can see from its name what it's doing?

2024-01-29 19:01 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
I think you've duplicated this file, and not deleted the old one, @kmilo9999! I can't see any changed you made in this file.

2024-01-29 19:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
I deleted the old file. Let me know if you still cant see the changes in this file

2024-01-29 21:28 UTC, hollandjg reviewed
I've a couple of questions around the edges – nothing major. It looks like just moving the file b05 and then reformatting it.

2024-01-29 21:28 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +    from scipy.ndimage import label
Depending on the results of the other discussion, I think we might want to move this import to the top of the file.

2024-01-29 21:28 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +from numba import jit
Do we need this line? I don't think we're using the import anywhere.

2024-01-30 16:37 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +    from scipy.ndimage import label
Done!

2024-01-30 16:38 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +from numba import jit
I removed this import and the code still runs locally. Let's see how it behaves on  the CI

2024-01-30 23:08 UTC, hollandjg approved these changes
Looks good to me!

2024-01-31 21:27 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
#97

2024-01-31 21:32 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
#98

2024-01-31 21:34 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
Camilo needs to use `git move`

2024-01-31 21:35 UTC, merged