Feature step7 integration
brown-ccv/icesat2-tracks pull request #53
Opened 2024-01-03 22:05 UTC by kmilo9999

- Add analysis_db/B06_correct_separate_var.py for step 7
- Cleaned code
- Formatted file

2024-01-30 23:25 UTC, hollandjg reviewed
Hey Camilo, thanks for this! I've one general question – was the removal of the "B2" regridded data throughout intentional? What's the source for that? Otherwise I've got a couple of comments.

2024-01-30 23:25 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +
Looks like this bit is in the wrong place – all imports should be under the docstring

2024-01-31 21:43 UTC, kmilo9999 commented
> Hey Camilo, thanks for this! I've one general question – was the removal of the "B2" regridded data throughout intentional? What's the source for that? Otherwise I've got a couple of comments.

We checked this with John in the dev meeting. The files should be compared against the `basic-sliderule` branch.

2024-02-01 17:30 UTC, cpaniaguam submitted a review, later dismissed
I say merge for now and refactor later.

If you like, consider moving all function definitions that happen in the middle of the script  to the top just after the import statements. I also saw an import statement in the middle that might have slipped through the cracks. But I can do all of this later when implementing the cli!

2024-02-01 17:30 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    )  # regridding heights
This can be refactored to something like this but it's tricky to tell it works as it should. To be safe better wait for test suite.
```suggestion
def save_table(data, tablename, save_path):
    try:
        io.save_pandas_table(data, tablename, save_path)
    except Exception as e:
        tabletoremove = save_path + tablename + ".h5"
        print(e, f"Failed to save table. Removing {tabletoremove} and re-trying..")
        os.remove(tabletoremove)
        io.save_pandas_table(data, tablename, save_path)

B06_ID_name = "B06_" + ID_name
table_names = [B06_ID_name + suffix for suffix in ["_B06_corrected_resid", "_binned_resid"]]
data = [B2_v2, B3_v2]

for tablename, data in zip(table_names, data):
    save_table(data, tablename, save_path)
```

2024-02-01 17:30 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +Gx
```suggestion
```

2024-02-01 17:30 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    return height_model, np.nan, dist_nanmask
Maybe move function definitions to the top after the imports? To me it feels like they're in the way.

2024-02-01 18:07 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    plt,
#100

2024-02-01 18:16 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    return height_model, np.nan, dist_nanmask
We can do a refactor by moving all this functions to a separate file, so B06_correct_separate_var only contains the logic applied to step 7. This can also be done to all the other steps.

2024-02-01 18:19 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    return height_model, np.nan, dist_nanmask
I like this idea!

2024-02-01 18:32 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    )  # regridding heights
I like this suggestion, pro-coding style. I dont see a reason why not to include it. I just did and it works as expected.

2024-02-01 18:32 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +Gx
done

2024-02-01 19:35 UTC, cpaniaguam requested changes
Just one more change I think you might have missed! I put it in a suggestion.

2024-02-01 19:35 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    from scipy.ndimage.measurements import label
```suggestion
```

2024-02-01 20:01 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    from scipy.ndimage.measurements import label
Done!

2024-02-02 01:22 UTC, cpaniaguam approved these changes

2024-02-02 02:12 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    return height_model, np.nan, dist_nanmask
#103

2024-02-02 02:12 UTC, merged