fix: isolate data pull
brown-ccv/icesat2-tracks pull request #80
Opened 2024-01-22 21:20 UTC by cpaniaguam

Changes:
- Move data pull instructions to a function to the `io` module for testing purposes
- Throw error if geodataframe pulled from sliderule is empty
- Other cleanups: formatting, commented code, ...

2024-01-24 21:58 UTC, hollandjg reviewed
I've some general comments on this! Let me know what you think.

2024-01-24 21:58 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
>          import re
It might be a good idea to move this import to the top of the file – you can get weird behavior with imports in function bodies.

2024-01-24 21:58 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
> +        raise Exception("Empty Geodataframe. No data could be retrieved.")
You might want to make this into a more specific Exception, like [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError)

2024-01-24 21:58 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
George had a great problem last week on HNN – they also had a file called `io.py`, and its existence caused the debugger to break (he would set breakpoints but they'd be ignored).

We should probably rename this to `io_.py` or something like that, to avoid weird errors.

2024-01-24 21:58 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
>              self.hemis = self.hemis
This doesn't do anything, right?

2024-01-24 21:58 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
>          os.makedirs(save_path)
You could make this shorter using [`pathlib.Path.mkdir`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir)

2024-01-24 21:58 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
>      from pandas.io.pytables import PerformanceWarning
same comment here – might be better to move these imports to the top of the file.

2024-01-24 21:58 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
Pulling all the imports to the top of the file might be a valuable thing to do here – it'll probably run faster, and it's more pythonic too.

2024-01-29 16:00 UTC, kmilo9999 commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
I agree with this comment. What about rename it to `icesat_io_tools.py`. vscode can refactor all the dependencies in the project.

2024-01-29 16:02 UTC, kmilo9999 requested changes
What about rename the `io.py file`  to ` icesat_io_tools.py` ? vscode can refactor all the dependencies in the project.

2024-01-29 17:14 UTC, cpaniaguam commented
> What about rename the `io.py file` to ` icesat_io_tools.py` ? vscode can refactor all the dependencies in the project.

What about `iotools`?

2024-01-29 19:04 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
I'm not sure about including "icesat" at the start – it seems like duplication to me.
I definitely agree that we should use the IDE to do the renaming and get everything in one go.

2024-01-29 19:17 UTC, hollandjg commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
>          import re
Sure! This is just the recommendation from [PEP8](https://peps.python.org/pep-0008/#imports):

> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.

They write at the top:

> A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important.
> 
> However, know when to be inconsistent – sometimes style guide recommendations just aren’t applicable. When in doubt, use your best judgment. Look at other examples and decide what looks best. And don’t hesitate to ask!

If there's a strong reason to import in the function body, of course we can disregard PEP8. I don't see there being a strong reason here (but if there's something you all see that I don't, then no problem).

Some of the weird behavior I've seen in the past was stuff like:
- You're trying to compare whether two equivalent objects are equal and they look equal, but they don't act equal because they weren't created from the same copy of the imported package.
- You set a breakpoint in a function, but it never gets hit because the debugger doesn't see the imported files as the same.

Other things I could imagine:
- There's some code which runs when the module is imported and is only meant to be run once, but because it's imported multiple times it runs more than once and leads to a weird state.

2024-01-30 20:59 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
I went with `iotools`.

2024-01-30 21:47 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/io.py
>              self.hemis = self.hemis
Refactored the whole if block to an easier to maintain mapping.

2024-02-01 20:15 UTC, kmilo9999 approved these changes
Looks good to me

2024-02-01 21:07 UTC, merged