CLI Tools, CLI for Step 1
brown-ccv/icesat2-tracks pull request #88
Opened 2024-01-31 17:46 UTC by cpaniaguam

To facilitate reviewing #78, we are splitting it into bite-size chunks. This is the first one.

Changes:
1. **Update: Dependencies and CI Runner for Step 1**
   Add `typer` and others. The CI runner for Step 1 has also been updated to reflect these changes.

2. **Feature: CLI Tools for Step 1**
   CLI tools for the package and the particular cli for Step 1. It includes argument parsing and validation, and improved feedback output.

2024-02-05 19:00 UTC, hollandjg requested changes
Hey Carlos, thanks for the PR! I've taken a look and I have a few comments and questions – perhaps we can talk this through tomorrow?

2024-02-05 19:00 UTC, hollandjg commented on .github/workflows/test-B01_SL_load_single_file.yml
> -        run: python src/icesat2_tracks/analysis_db/B04_angle.py SH_20190502_05180312 SH_testSLsinglefile2 True
It looks like you're removing all the tests here, rather than just refactoring the first one. Is it possible to leave the steps 2...7 in?

2024-02-05 19:00 UTC, hollandjg commented on pyproject.toml
> +  "pytest-xdist >=3.5.0, < 4.0.0",
Are these dependencies required for the package itself? We might want to put them under "development dependencies" instead.

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    with suppress_stdout():
What's the motivation for suppressing stdout here? That looks like a change in behavior which might make debugging more tricky. 

You could consider changing "print" statements to something using the "logging" module, and then make it so you can run the code using "--verbose" on the command line to print all the output.

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +        )  # loads standard experiment
... or might it be better just to set track_name, batch_key and ID_flag (test_flag) directly using typer arguments in the function definition and completely remove io.init_from_input? 

It looks like that function's main purpose is to parse the command line arguments or introduce some pre-defined values – perhaps we can get away without the pre-defined values (or have them also set using the typer arguments to the function)?

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    echo("STARTS", "white")
I'd be careful with modifying text colors for terminals. I use a white background with black text, so I won't be able to read this. 

Is there a strong reason other than aesthetics to modify this? If not, we should just leave these as `print` functions for now and prettify later, if it turns out to be important for the PI.

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    echoparam("ID_name", ID_name)
For these you could use:
`print(f"{ID_name=}")` which will print out 
`ID_name=<value of ID_name>`

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/clitools.py
> +    return workdir, plotsdir
What happens if output_dir is empty?
You'll return workdir and plotsdir both as None – is that intended?

It might be a good idea to put in some doctests of this function which shows your intention around how this function should be used, and what its behavior is in edge cases.

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/clitools.py
> +            sys.stdout = old_stdout
Are you sure you want this function? Seems a bit risky – might make your debugging life harder.

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/clitools.py
> +    )
I think you'll want some doctests here as well – known correct and malformed strings and a demonstration that they get parsed properly.

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/clitools.py
> +    )
Same here – documentation and some doctests would be marvellous!

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/clitools.py
> +    return str(path)
Is this doing the right check? Don't you make the output directories later anyway, so checking if they exists shouldn't be necessary. The program will just throw an error if it can't make them exist. 

Again, doctests would be good here!

2024-02-05 19:00 UTC, hollandjg commented on src/icesat2_tracks/clitools.py
> +def report_input_parameters(heading: str = "** Input parameters:", **kargs):
the usual syntax for this kind of catchall is `**kwargs` rather than `**kargs` (keyword-args)

2024-02-05 20:16 UTC, cpaniaguam commented on .github/workflows/test-B01_SL_load_single_file.yml
> -        run: python src/icesat2_tracks/analysis_db/B04_angle.py SH_20190502_05180312 SH_testSLsinglefile2 True
I don't intend to merge this to main without all the cli/tests for each of the steps in place in this PR. The tests are meant to run in parallel. Keeping the old structure would be counterproductive here. This file won't need any changes as #90, #92, #94, and future PRs for steps 5-7 are merged into this branch.

2024-02-05 20:17 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +        )  # loads standard experiment
#106

2024-02-05 20:36 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    with suppress_stdout():
The motivation for suppressing stdout is to have the tests run as quickly as possible. This is probably the easiest way to optimize these scripts as they produce a lot of output. This context manager still displays error messages.
```python
>>> with suppress_stdout():
...     print('hello')
...
>>> with suppress_stdout():
...     assert False
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AssertionError
>>> with suppress_stdout():
...     1/0
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero
```

2024-02-05 20:38 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    with suppress_stdout():
#107

2024-02-05 20:42 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    with suppress_stdout():
I will add an extra parameter `verbose : Bool` to the context manager and the cli app to have control over displaying print calls to stdout.

2024-02-05 20:49 UTC, cpaniaguam commented on src/icesat2_tracks/clitools.py
> +            sys.stdout = old_stdout
See https://github.com/brown-ccv/icesat2-tracks/pull/88#discussion_r1478882829

2024-02-05 20:52 UTC, cpaniaguam commented on src/icesat2_tracks/clitools.py
> +def report_input_parameters(heading: str = "** Input parameters:", **kargs):
Thanks for catching this typo! I'll update it :)

2024-02-06 17:07 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +            Ti[kk]["heights_c_std"] = Ti[kk]["h_sigma"].copy()
Here we are silencing the warnings from pandas, right ? 
@hollandjg  Is there a way to differentiate when the app runs in dev mode and when it's in distrib/release mode?
We could turn on the warning messages in dev mode and silence them in release.

2024-02-06 17:07 UTC, kmilo9999 approved these changes
It looks good to me. 
I left a comment below about the warnings

2024-02-07 15:15 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +            Ti[kk]["heights_c_std"] = Ti[kk]["h_sigma"].copy()
You could do something like:
- Have a `--debug` or `--verbose` flag on the command line
- Run the `warnings.simplefilter(...)` function if that flag is `False`

2024-02-07 15:56 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +            Ti[kk]["heights_c_std"] = Ti[kk]["h_sigma"].copy()
Those context managers in L192-195 are handling the `SettingWithCopyWarning` only.
```python
        with warnings.catch_warnings():
            warnings.simplefilter(
                "ignore", category=SettingWithCopyWarning
            )  # TODO: remove when warnings are handled
```

2024-02-07 16:58 UTC, kmilo9999 reviewed
It looks good to me. 
I think John has a comment about checking the state of parameters in the  `def update_paths_mconfig(output_dir, mconfig)` function.
After solving it, I think is ready to go.

2024-02-07 17:34 UTC, cpaniaguam commented on src/icesat2_tracks/clitools.py
> +    return workdir, plotsdir
I will change `run_B01_SL_load_single_file`'s signature to make it a required argument and simplify the logic here. Thanks!

2024-02-07 18:17 UTC, kmilo9999 approved these changes
👍

2024-02-07 20:04 UTC, hollandjg requested changes
One more small comment here, and we should still decide on the function names question.

2024-02-07 22:04 UTC, cpaniaguam commented on pyproject.toml
> +test = ["coverage", "pytest >=7.4.4, <8.0.0", "pytest-xdist >=3.5.0, <4.0.0"]
I'll apply this patch in #111 so it cascades down to this PR.

2024-02-09 16:06 UTC, kmilo9999 approved these changes
Looks good to me!

2024-02-09 19:18 UTC, hollandjg approved these changes
Looks good to me!

2024-02-12 19:57 UTC, hollandjg approved these changes
Looks good to me!

2024-02-12 19:57 UTC, hollandjg commented on src/icesat2_tracks/clitools.py
> +                sys.stdout = old_stdout
There's a function provided in python 3.4+ which does this – please use that instead!

Check out https://stackoverflow.com/a/37989355/5542581:
```python
import contextlib

with contextlib.redirect_stdout(None):
    print("will not print")

print("this will print")
```

2024-02-12 20:23 UTC, cpaniaguam commented on src/icesat2_tracks/clitools.py
> +                sys.stdout = old_stdout
Interesting, thanks for the suggestion @hollandjg! I adapted the current implementation from a context manager that was available elsewhere in the repo. 

It seems like `contextlib.redirect_stdout` is somewhat limited for this use case, however, as it doesn't have the flexibility to do conditional suppression. Can you think of a simple way to refactor the currently implemented `suppress_stdout` so that it leverages `contextlib.redirect_stdout`? I gave it some thought but couldn't come up with anything straightfoward.

2024-02-17 07:15 UTC, merged