feat: add cli to step 2 -- B02_make_spectra_gFT.py
brown-ccv/icesat2-tracks pull request #90
Opened 2024-01-31 18:34 UTC by cpaniaguam

Also update command for CI.
#89

2024-02-06 18:42 UTC, kmilo9999 requested changes
It looks good to me. Just a small change in the name of the function.

2024-02-06 18:42 UTC, kmilo9999 commented on src/icesat2_tracks/app.py
> +def makespectra(
According to the python naming convention, function methods should have words separated by underscores
what about:  make_spectra?

2024-02-07 16:21 UTC, cpaniaguam commented on src/icesat2_tracks/app.py
> +def makespectra(
Yes, that is correct. That's indeed one of the guidelines on naming functions. However, the goal here is to have the corresponding cli command be `makespectra` so that the two names are consistent.

2024-02-07 20:14 UTC, hollandjg reviewed
A few more comments on here

2024-02-07 21:07 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    step2app()
I will rename it to something like `make_spectra_app`.

2024-02-08 19:23 UTC, cpaniaguam commented on src/icesat2_tracks/app.py
> +def makespectra(
This change will be applied in #111

2024-02-08 20:26 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +        plt.show()
Also, I am not sure this will work as the `mconfig` object is imported from `.config.IceSAT2_startup` which also imports `matplotlib`. I think the plotting instructions might need to be put in a separate module. However, when running things locally I don't see any plot windows pop.

2024-02-08 20:56 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    k = all_beams[0]
I am not really sure why or how this got changed. In the original file that line reads `all_beams[0]` but then it got changed to `all_beams[1]` in commit [f48f904](https://github.com/brown-ccv/icesat2-tracks/commit/f48f904517c433029774c95a16b756285a45c74e?diff=split&w=1#:~:text=%5B0%5D-,k%20%3D%20all_beams%5B1%5D,-for%20k%20in)? I'm guessing the former should be the correct one. @kmilo9999 what do you think?

2024-02-08 20:58 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    step2app()
#111

2024-02-09 14:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    k = all_beams[0]
`all_beams[1]` is the value set in the `basic_sliderule` branch. That's the code that implements the new pipeline. So, I assume that the former is the right one.

2024-02-09 14:45 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    k = all_beams[0]
Very well, I'll change it back to `all_beams[1]`. Thanks!

2024-02-09 14:56 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    k = all_beams[0]
Having looked at the code below that line, it seems like `k` was being used experimentally at some point. In the for loop below that name is used as a loop variable so it'll delete it.

2024-02-09 15:00 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    with suppress_stdout():
I think the suppression should go in each of the app functions. The goal is to suppress all output except error messages.

2024-02-09 15:23 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +    k = all_beams[0]
I am re-reviewing this PR. It seem `make_spectra.py`  has some incorrect value that need to be re-adjusted to the ones set in the main branch.

2024-02-09 15:38 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +            heights_c_std = io.get_beam_var_hdf_store(Gd[k], "dist")
The main and basic_silderule branches name the second parameter `x` : 
`io.get_beam_var_hdf_store(Gd[k], "x")`

2024-02-09 15:38 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +        dist = io.get_beam_var_hdf_store(Gd[list(Gd.keys())[0]], "dist")
same here, the main branch and sliderule branches the second argument is `x`

2024-02-09 15:39 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
> +            dist_i = io.get_beam_var_hdf_store(Gd[k], "dist")
Same here , main and basic_sliderule branches the second parameter value is `x`

2024-02-09 15:46 UTC, kmilo9999 requested changes
Some values in the make_spectra file come from the pre-new pipeline version. I added comments of the changed values. Those are the ones I noticed.

2024-02-09 18:34 UTC, kmilo9999 reviewed
Looks good to me. Let's  wait for John's review.

2024-02-12 20:00 UTC, hollandjg reviewed
Looks good to me!

2024-02-12 20:01 UTC, hollandjg approved these changes

2024-02-17 06:40 UTC, merged