feat: cli step 2 -- b03_plot_spectra_ovpy
brown-ccv/icesat2-tracks pull request #92
Opened 2024-01-31 19:10 UTC by cpaniaguam

#91

2024-02-06 20:00 UTC, kmilo9999 requested changes

2024-02-06 20:00 UTC, kmilo9999 commented on src/icesat2_tracks/app.py
> +def plotspectra(
```suggestion
def plot_spectra(
```
Separate the words using an underscore.

2024-02-06 20:08 UTC, cpaniaguam commented on src/icesat2_tracks/app.py
> +def plotspectra(
I could make this change. But in the interest of keeping name consistency, the corresponding [cli command](https://github.com/brown-ccv/icesat2-tracks/blob/84941b432ed3fd68e4364df656174126b22ca4eb/pyproject.toml#L162) is named `plotspectra` (no `_` or `-`) so users don't have to type as much. What do you think?

2024-02-06 21:35 UTC, kmilo9999 commented on src/icesat2_tracks/app.py
> +def plotspectra(
I was checking the python naming conventions, but it seems the command line names have a different kind of nomenclature.
Also, It seems like typer transforms `_`  in a @app name's function  to a `-`  in the command line.  The  `delete_all`  in the example [here](https://typer.tiangolo.com/tutorial/commands/options/) . Would that work ?
@hollandjg  any thoughts ?

2024-02-07 19:32 UTC, hollandjg commented on src/icesat2_tracks/app.py
> +def plotspectra(
I'd be tempted to make them all consistently `names_with_underscores` (and it sounds like those would become `names-with-underscores` on the command line) so that it's totally clear what is what – the name on the command line refers to a python function with a corresponding name.

2024-02-07 22:01 UTC, cpaniaguam commented on src/icesat2_tracks/app.py
> +def plotspectra(
This patch will be applied with #111.

2024-02-09 16:41 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +matplotlib.use("Agg")  # prevent plot windows from opening
I wonder if we could move this line to the top, right next to `import matplotlib`

2024-02-09 17:08 UTC, kmilo9999 reviewed
I only had a comment in the PR. The rest of the logic looks good and similar to the one in the `basic_sliderule` branch. If the workflow works, then it's fine by me.

2024-02-09 18:03 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
> +matplotlib.use("Agg")  # prevent plot windows from opening
I can see why one would like to do that. However, this isn't an import statement so by convention it should go in a separate block. Another reason for placing it outside the import block would be for programmatically getting all project deps by looking at the headers but this one file would require cleaning up!

2024-02-12 18:09 UTC, kmilo9999 approved these changes

2024-02-12 20:04 UTC, hollandjg approved these changes
Let's merge!

2024-02-17 06:10 UTC, merged