93 cli step 4 a02c iowaga thredds priorpy
brown-ccv/icesat2-tracks pull request #94
Opened 2024-01-31 19:37 UTC by cpaniaguam

At the time of the push a service used was unavailable:

> syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
> 
> context:
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html>
>     <head>
>         <title>503 Service Unavailable</title>
>     </head>
>     <body>
>         <h1>Service Unavailable</h1>
>         <p>
>             The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
>         </p>
>     </body>
> </html>
> 
> Traceback (most recent call last):
> 
>   File "/home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
>     file = self._cache[self._key]
> 
>   File "/home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
>     value = self._cache[key]
> 
> KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('https://tds3.ifremer.fr/thredds/dodsC/IOWAGA-WW3-FORECAST_GLOBMULTI_GLOB-30M_FIELD_NC_MARC_WW3-GLOB-30M',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '340f4832-a177-48f4-bab5-7e566c52c72b']

2024-02-02 19:32 UTC, kmilo9999 reviewed
This one runs in the CI. Should I go ahead with the review or wait for the other steps to merge?

2024-02-02 19:39 UTC, cpaniaguam commented
@kmilo9999 Feel free to review it!

2024-02-03 00:09 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +matplotlib.use("Agg")  # prevent plot windows from opening
it seems we can move this line right next to the 
`import matplotlib` line

2024-02-03 00:17 UTC, kmilo9999 requested changes
I added some comments. So many things we can do to improve the readability of the script

2024-02-03 00:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +import matplotlib
`import matplotlib; matplotlib.use("Agg")`

2024-02-03 00:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +    file_name_base = "LOPS_WW3-GLOB-30M_"
this variables is use until line 331. We could probably move it to a better spot were makes sense to declare it

2024-02-03 00:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +    var_list = [
This is a constant list. I think we can move it to the so called constant file we talked about

2024-02-03 00:17 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +        name_dict={
same here. A list of constant values

2024-02-06 19:34 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +matplotlib.use("Agg")  # prevent plot windows from opening
Most linters complain about having multiple statements in one line -- l guess it makes things less readable. Also, we'd be mixing import statements with non-import statements.

2024-02-06 19:54 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +    file_name_base = "LOPS_WW3-GLOB-30M_"
Moving it closer to L331.

2024-02-06 19:56 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +        name_dict={
#65

2024-02-07 20:46 UTC, hollandjg requested changes
Hey Carlos, it feels like we're making a lot of progress here. A few comments and suggestions.

2024-02-07 20:46 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +matplotlib.use("Agg")  # prevent plot windows from opening
I agree, this should come after all the imports.

2024-02-07 20:46 UTC, hollandjg commented on .gitignore
> +.venv39/
This looks like a duplicate of line 51 in this file

2024-02-07 20:46 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
Just noticed this: we should probably update the shebang lines to `#!/usr/bin/env python3` across the whole project.

2024-02-09 15:26 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +            "IOWAGA-WW3-FORECAST_GLOBMULTI_GLOB-30M_FIELD_NC_MARC_WW3-GLOB-30M"
How to do this matching? The key probably depends on the data set pulled. I'll create an issue to maybe address this later. #114

2024-02-09 15:26 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
> +        data_url = "https://tds3.ifremer.fr/thredds/IOWAGA-WW3-FORECAST/IOWAGA-WW3-FORECAST_GLOBMULTI_GLOB-30M.xml"
#114

2024-02-09 17:17 UTC, kmilo9999 reviewed
Looks good to me.  We should be able to merge if John doesnt have ant additional feedback.

2024-02-12 18:10 UTC, kmilo9999 approved these changes

2024-02-12 20:06 UTC, hollandjg approved these changes
Looks good to me!

2024-02-17 05:37 UTC, merged