feat: isolate test suite
brown-ccv/icesat2-tracks pull request #99
Opened 2024-02-01 15:30 UTC by cpaniaguam

- Add test data files for steps 2-5. This includes new data sets that will be used for testing the functionality of steps 2 through 5
- Handle tar.gz files via Git Large File Storage (LFS)
- Add tests for step 1. 

Once PRs #90, #92 , #94 (cli's for steps 2-4) are merged the commented code in `test_steps.py` can be uncommented and then update the CI workflow to run all tests via the test suite.

#96

2024-02-01 20:13 UTC, kmilo9999 requested changes
How you feel about renaming the CI workflow file. `test.yml` is too general.

2024-02-01 20:57 UTC, cpaniaguam commented
> How you feel about renaming the CI workflow file? `test.yml` is too general.

I am open. What would be a better name? Naming things is sometimes tricky! @kmilo9999

2024-02-01 21:46 UTC, kmilo9999 commented
> Reference

what about `test_icesat2_pipeline.yml`. The value of the name tag can be changed to the same name

2024-02-02 19:09 UTC, kmilo9999 commented
> > I dont know. We can rename the file again if new pipelines appear and there's a way to distinguish between them.
> 
> Do you believe in [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)? @kmilo9999

I do believe in it. I just want to have a clear idea that the file runs the pipeline's tests.

2024-02-12 18:34 UTC, kmilo9999 commented
Review and merge this PR after CLI full integration.

2024-02-12 20:10 UTC, hollandjg requested changes
(Just marking this as needing changes – uncommenting the commented-out tests – so it disappears from the list of needed reviews. Thanks!)

2024-02-26 05:28 UTC, kmilo9999 commented on tests/test_steps.py
> +    # test_step7()  # passing
Are these lines meant to be commented ?

2024-02-26 07:41 UTC, cpaniaguam commented on tests/test_steps.py
> +    # test_step7()  # passing
Yes, but this entry point was being used during development. I'll delete it.

2024-02-26 14:47 UTC, kmilo9999 reviewed
Looks good to me. Great work Carlos.
My only comment would be that because of the changes in the workflow file, we are losing all the logs from all the steps. What are your thoughts @hollandjg @cpaniaguam ?

2024-02-26 15:11 UTC, cpaniaguam commented
> Looks good to me. Great work Carlos. My only comment would be that because of the changes in the workflow file, we are losing all the logs from all the steps. What are your thoughts @hollandjg @cpaniaguam ?

@kmilo9999 I used the steps names and commands in the workflow file to update the readme with a sample data processing workflow here: https://github.com/brown-ccv/icesat2-tracks/pull/130. Feel free to take a look at that one as well!

2024-02-26 15:37 UTC, kmilo9999 commented
> > Looks good to me. Great work Carlos. My only comment would be that because of the changes in the workflow file, we are losing all the logs from all the steps. What are your thoughts @hollandjg @cpaniaguam ?
> 
> @kmilo9999 I used the step names and commands in the workflow file to update the readme with a sample data processing workflow here: #130. Feel free to take a look at that one as well!

Yes, I noticed that. I was talking about something like:
`Each command is provided with a HELP command that explain the mandatory and optional arguments. Just type command_name --HELP `

What are your thoughts on losing/hiding the logs of the steps ?

2024-02-26 16:48 UTC, hollandjg requested changes
Hi Carlos, thanks for this! It looks like a well thought through method of isolating the testing of each of the steps.
I've got some suggestions for simplifications and changes, and some requests for more info!

2024-02-26 16:48 UTC, hollandjg commented on .gitattributes
Was there a step you needed to do to make git clone the LFS files? I'd include that in the readme.

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
> +# Script 1 is different than the others because it doesn't have any input data and uses a different track name.
You could make the `create_script` function take the track name as an argument to solve that. Would you have to do something similar with the input data?

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
This looks a bit complex. Please could you include some more documentation at the top of the file to say how to add new tests (when we refactor parts of the code and merge or split steps) or run the tests for other tracks?

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
> +    t2 = check_B03_freq_reconst_x()
I'm not sure this abstraction makes the code easier to read. The function name doesn't really help me understand what the check is doing. Would it be simpler to just fold in the checks from `check_B03_freq_reconst_x` directly into this test function?

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
> +    t1 = run_test(script3, paths3)
You could just assert directly on this line – then if it fails, the code in the second part of the check wouldn't even run.

2024-02-26 16:48 UTC, hollandjg commented on .github/workflows/test_icesat2_tracks_pipeline.yml
> +        run: pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=auto tests/test_steps.py
Are the tests intended to be faster already? It looks to me like they still take on the order of 20 minutes with the new test suite – a speed-up of about 2 minutes.

2024-02-26 16:48 UTC, hollandjg commented on .gitignore
> +/tests/input-data
Looks like you have two different filepath conventions going on here.

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
> +    homedir = Path(__file__).parent
Did you consider using a temporary directory generated by python, outside of the working tree, for each of the test cases? Then you wouldn't need to worry about tearing down the test suite at the end – Python would do it for you. 

Could you make it so that you unzip the tarball into some arbitrary directory and then just run the script there, and it should work? Each test script could use a fixture which makes its working directory (which would be created by pytest), then populates it with files, then runs the test, and then automatically tears it down at the end.

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
> +    for tarball in input_data_dir.glob("*.tar.gz"):
Did you think about not building all the test directories in one go, but instead unzipping the data for each test case just before running the specific test case? That might make it easier to treat the tests as truly independent.

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
> +        kwargs["stderr"] = subprocess.DEVNULL
Can you say why you decided to suppress the output here?
if you run in verbose mode, does that set `suppress_output` to `False`?

2024-02-26 16:48 UTC, hollandjg commented on tests/test_steps.py
> +    return all(result)
Since you're looping through these anyway, it might be simpler to do this check within the for-loop itself
```suggestion
    print("\n")
    # report which files are missing (in red) and which are present (in green)
    for pth in paths:
        if Path(pth).is_file():
            print(f"\033[92m{pth} is present\033[0m")
        else:
            print(f"\033[91m{pth} is missing\033[0m")
    return all(result)
```

2024-02-26 16:48 UTC, hollandjg commented on .github/workflows/test_icesat2_tracks_pipeline.yml
> +        run: pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=auto tests/test_steps.py
Did you consider a much simpler approach – saving the output of step 1 and just unzipping that into the working directory, then running all the tests sequentially? You may want to do that as well – that would keep the end-to-end testing intact, but would still give you quick feedback if something broke. You could have both sets of tests (e2e and the ones from this PR) run in parallel in two different workflows (or two different jobs in one workflow).

2024-02-26 16:59 UTC, cpaniaguam commented on .github/workflows/test_icesat2_tracks_pipeline.yml
> +        run: pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=auto tests/test_steps.py
> because we won't be able to see what happened when a test failed, especially if it's a transient failure.

The `--tb=long` option sets up `pytest` to pruduce _exhaustive, informative traceback formatting_  when an error occurs. More on this [here](https://docs.pytest.org/en/7.1.x/how-to/output.html).

> I'd also say that this workflow looks a bit less useful than the previous one – previously, the workflow file served an additional role of documenting how to run the pipeline for a single track, but now it's a fairly cryptic test script. Is there anything you could do to retain that documentation?

Please see #130 on documentation on how to run the pipeline for a single track.

2024-02-26 17:01 UTC, cpaniaguam commented on .gitattributes
See #130

2024-02-26 17:04 UTC, cpaniaguam commented on .github/workflows/test_icesat2_tracks_pipeline.yml
> +        run: pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=auto tests/test_steps.py
The current workflow will be kept and a new one with the test suite will be added.

2024-02-26 17:16 UTC, cpaniaguam commented on tests/test_steps.py
> +    return all(result)
Thanks for this suggestion @hollandjg. Note that I am using the `result` list as the return object in combination with the `all` function. The suggested approach would require creating an empty list for `result` and populate it within the for loop  that adds the convenient side effect of displaying what files are present/absent with color. I am trying to avoid that pattern with the list comprehension, which is the pythonic way of performing such tasks. What do you think?

2024-02-26 17:42 UTC, cpaniaguam commented on tests/test_steps.py
> +    for tarball in input_data_dir.glob("*.tar.gz"):
I think that in the current design the tests are indeed independent. The `setup_module` fixture sets the state for all the tests in the test suite placing the input data for each of them and it's run once before any tests are run. The `run_test` function doesn't do any setup work; it only processes data and returns a boolean. It's a `pytest` design pattern. With the input data for each test in place, the tests are run in parallel, independently from each other.

2024-02-26 17:52 UTC, cpaniaguam commented on tests/test_steps.py
> +    assert run_test(script1, paths1, delete_paths=False)  # passing
I understand this point of view, but this looks a lot more complex to me and requires a lot more cognitive effort to understand, especially if one is having to look at this file more than once. I think using variables to represent those objects reduces the reader's cognitive load and makes the file easier to read. @kmilo9999 what do you think?

2024-02-26 19:09 UTC, cpaniaguam commented on .github/workflows/test_icesat2_tracks_pipeline.yml
> +        run: pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=auto tests/test_steps.py
I added the old serial workflow file and it took that run ~24 minutes. With the test suite it took ~20 minutes using the maximum 4 cores of a gh actions runner. On my computer using 4 cores it takes under 10 minutes. Your millage may vary, but on average the test complete faster using the test suite.

2024-02-26 19:33 UTC, cpaniaguam commented on tests/test_steps.py
> +        kwargs["stderr"] = subprocess.DEVNULL
Here is an excerpt of what one will see if output is not suppressed in this way, even when the scripts' `--no-verbose` flag is used.
```shell
(.venv) ➜  icesat2-tracks git:(96-isolate-test-suite) ✗ pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=4 tests/test_steps.py
Test session starts (platform: linux, Python 3.9.18, pytest 7.4.4, pytest-sugar 0.9.7)
cachedir: .pytest_cache
rootdir: /home/cpaniaguam/icesat2-tracks
plugins: durations-1.2.0, xdist-3.5.0, sugar-0.9.7
4 workers [7 items]     collecting ... 
scheduling tests via LoadScheduling
/home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/icesat2_toolkit/spatial.py:49: ImportWarning: GDAL not available
  warnings.warn("GDAL not available", ImportWarning)
<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject
/home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/icesat2_toolkit/spatial.py:49: ImportWarning: GDAL not available
  warnings.warn("GDAL not available", ImportWarning)
<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject
/home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/icesat2_toolkit/spatial.py:49: ImportWarning: GDAL not available
  warnings.warn("GDAL not available", ImportWarning)
<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject
/home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/icesat2_toolkit/spatial.py:49: ImportWarning: GDAL not available
  warnings.warn("GDAL not available", ImportWarning)
<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject

 tests/test_steps.py::test_step3 ✓                                                                                                                                                                                                                                                                 14% █▌        /home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/icesat2_toolkit/spatial.py:49: ImportWarning: GDAL not available
  warnings.warn("GDAL not available", ImportWarning)
<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject


 tests/test_steps.py::test_step4 ✓                                                                                                                                                                                                                                                                 29% ██▉       
[gw3] PASSED tests/test_steps.py 
 tests/test_steps.py::test_step2 ✓                                                                                                                                                                                                                                                                 43% ████▍     /home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/icesat2_toolkit/spatial.py:49: ImportWarning: GDAL not available
  warnings.warn("GDAL not available", ImportWarning)
<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject


 tests/test_steps.py::test_step6 ✓                                                                                                                                                                                                                                                                 57% █████▊    No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.


 tests/test_steps.py::test_step7 ✓                                                                                                                                                                                                                                                                 71% ███████▎  
[gw2] PASSED tests/test_steps.py 
 tests/test_steps.py::test_step1 ✓                                                                                                                                                                                                                                                                 86% ████████▋ /home/cpaniaguam/icesat2-tracks/.venv/lib/python3.9/site-packages/icesat2_toolkit/spatial.py:49: ImportWarning: GDAL not available
  warnings.warn("GDAL not available", ImportWarning)
<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject
```

I am removing this kind of output In the interest of getting a clean summary with test results at the end.

2024-02-26 20:14 UTC, cpaniaguam commented on tests/test_steps.py
> +    homedir = Path(__file__).parent
> Did you consider using a temporary directory generated by python, outside of the working tree, for each of the test cases? Then you wouldn't need to worry about tearing down the test suite at the end – Python would do it for you.

Yes, I think I did. Note how `mkdtemp` is used for that very purpose. I decided to create the temp directory in the project's `tests/` directory rather than some random directory to facilitate monitoring. The teardown module cleans up afterwards.

> Could you make it so that you unzip the tarball into some arbitrary directory and then just run the script there, and it should work? Each test script could use a fixture which makes its working directory (which would be created by pytest), then populates it with files, then runs the test, and then automatically tears it down at the end.

I think something like that is actually happening already. The current implementation leverages the `setup_module` and `teardowm_module` to set up working directories for each test which are created by pytest.

2024-02-26 20:43 UTC, cpaniaguam commented on tests/test_steps.py
> +    t2 = check_B03_freq_reconst_x()
Perhaps some more context will help. The script produces plots in the `<output-dir>/plots/SH/<batch-key>/SH_<track-name>/B03_spectra` directory.

```shell
(.venv) $ tree <output-dir>/plots/SH/<batch-key>/SH_<track-name>/B03_spectra
<output-dir>/plots/SH/<batch-key>/SH_<track-name>/B03_spectra
├── B03_freq_reconst_x28.pdf
├── B03_freq_reconst_x47.pdf
├── B03_freq_reconst_x56.pdf
├── B03_freq_reconst_x66.pdf
└── B03_freq_reconst_x75.pdf

0 directories, 5 files
```

Note that the file names in this directory all  have the `B03_freq_reconst_x` prefix which is partly used for the function name which _checks_ that the correct count of such files are present in that directory.

Can you suggest a better name that would help facilitate understanding what the check is doing? Maybe adding this context to the function's docstring or documenting the issue with comment would be useful? Both? Neither?  As mentioned elsewhere, having the abstraction is useful if one needs to look at this code more than once.

2024-02-27 20:45 UTC, hollandjg commented on tests/test_steps.py
> +    return all(result)
Oh I see. Makes sense!

2024-02-28 16:49 UTC, tdivoll requested changes
The code looks good and it seems like many suggestions have already been incorporated. I just found some small text cleanups.

2024-02-28 16:49 UTC, tdivoll commented on .github/workflows/test_icesat2_tracks_pipeline.yml
>        - name: fouth step IOWAGA threads
```suggestion
      - name: fourth step IOWAGA threads 
```

2024-02-28 16:49 UTC, tdivoll commented on .github/workflows/test_icesat2_tracks_pipeline.yml
>              icesat2waves correct-separate --help # prelim name
Are `make-b04-angle` and `correct-separate` still prelim names? If not, delete the comments

2024-02-28 16:49 UTC, tdivoll commented on tests/test_steps.py
> +To this end, it sets up a temporary directory within the tests/ directory with subdirectories containing the required input data for each step. The tests are run in parallel using the xdist plugin, w
```suggestion
To this end, it sets up a temporary directory within the `tests/` directory with subdirectories containing the required input data for each step. The tests are run in parallel using the `xdist` plugin, with each worker having its own copy of the input data. This allows the tests to modify the input data without affecting other workers. The `setup_module` function (fixture) is responsible for creating the temporary directory and setting up the input data for each step. It also prepares the target directories for each step by extracting the necessary files from tarballs in the `tests/testdata` directory and organizing them in the appropriate directory structure.
```

2024-02-28 16:49 UTC, tdivoll commented on tests/test_steps.py
> +To create similar tests for other steps, you can use the `create_script` function to create the script and the `makepathlist` function to create the paths to the files that should be produced by the
Consider adding `()` to the end of each function. You do have the word function after each one so it should be obvious that these are functions. But `makepathlist()` rendered as code would stand alone without the text and it would be obvious that it's a function. I'm on the fence 🤷 .

2024-02-28 16:49 UTC, tdivoll commented on tests/test_steps.py
> +    Get a list of all file names in a directory
```suggestion
    Get a list of all file names in a directory.
```

2024-02-28 16:49 UTC, tdivoll commented on tests/test_steps.py
> +    "plots/SH/SH_testSLsinglefile2/SH_20190502_05180312/B01_track.png.png",
Just a double check -- should these have double `.png.png`?

2024-02-28 16:49 UTC, tdivoll commented on tests/test_steps.py
> +    When running in parallel using the xdist plugin, each worker will have its own copy of all the input data. This is necessary because the tests are run in parallel and the input data is modified b
```suggestion
    When running in parallel using the `xdist` plugin, each worker will have its own copy of all the input data. This is necessary because the tests are run in parallel and the input data is modified by the tests. This way, the teardown function can delete the temporary directory for each worker without affecting the other workers.
```

2024-02-28 18:24 UTC, cpaniaguam commented on .github/workflows/test_icesat2_tracks_pipeline.yml
>              icesat2waves correct-separate --help # prelim name
They are tentative still.

2024-02-28 18:43 UTC, cpaniaguam commented on tests/test_steps.py
> +    "plots/SH/SH_testSLsinglefile2/SH_20190502_05180312/B01_track.png.png",
Good catch! It turns out that the function that saves the images adds the extra suffix. I'll open an issue to address later.

2024-02-28 18:51 UTC, cpaniaguam commented on tests/test_steps.py
> +    "plots/SH/SH_testSLsinglefile2/SH_20190502_05180312/B01_track.png.png",
#135

2024-02-28 19:13 UTC, cpaniaguam commented
> The code looks good and it seems like many suggestions have already been incorporated. I just found some small text cleanups.

Thanks @tdivoll!

2024-02-29 16:10 UTC, tdivoll commented on .github/workflows/test_icesat2_tracks_pipeline.yml
>        - name: fouth step IOWAGA threads
Still needs update?

2024-02-29 16:13 UTC, tdivoll commented on tests/test_steps.py
> +    Get a list of all file names in a directory
Still not updated?

2024-02-29 16:15 UTC, tdivoll submitted a review, later dismissed
Just a couple formatting things that seem like they didn't come through in the last commit. I unresolved a couple of the comments to make it easier to find them.

2024-02-29 18:52 UTC, tdivoll approved these changes
Looks good to me!

2024-03-01 14:46 UTC, kmilo9999 approved these changes
looks good to me

2024-03-01 15:49 UTC, hollandjg approved these changes
Seems to work!

2024-03-01 16:10 UTC, merged